//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    
    public partial class CustomerByCompanyResult
    {
        public System.Guid BrinksCompany_Guid { get; set; }
        public string BrinksCompanyName { get; set; }
        public System.Guid MasterCustomer_Guid { get; set; }
        public string CustomerFullName { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
    }
}
