//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    
    public partial class PrevaultDepartmentBarcodeScanOutResult
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> JobGuid { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
        public string CommodityName { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.Guid> OnwardDestinationGuid { get; set; }
        public string OnwardDestinationName { get; set; }
        public Nullable<System.Guid> MappingInternalGuid { get; set; }
        public Nullable<System.Guid> MappingCommodityGuid { get; set; }
        public string Location { get; set; }
        public System.Guid CustomerLocationGuid { get; set; }
        public Nullable<int> ServiceJobTypeID { get; set; }
        public string ServiceJobTypeName { get; set; }
        public string ServiceJobTypeNameAbb { get; set; }
        public string ColumnInReport { get; set; }
        public Nullable<bool> FlagTVD { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<System.Guid> MasterRunResourceDaily_Guid { get; set; }
        public string DailyRunResource { get; set; }
    }
}
