//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    
    public partial class RunControlValidateEMPRequestOTCResult
    {
        public System.Guid MachineGuid { get; set; }
        public string MachineLockID { get; set; }
        public string SerialNumber { get; set; }
        public string MachineID { get; set; }
        public int FlagMultipleLock { get; set; }
        public int FlagValidTeam { get; set; }
        public Nullable<int> NotEnoughUpper { get; set; }
        public Nullable<int> NotEnoughLower { get; set; }
    }
}
