//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    
    public partial class RunResourceByGroupDetailAndWorkDayResult
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> MasterRunResourceShift { get; set; }
        public Nullable<System.Guid> MasterRouteGroup_Detail_Guid { get; set; }
        public string RouteGroupDetailName { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> RunResourceDailyStatusID { get; set; }
        public bool FlagRouteBalanceDone { get; set; }
    }
}
