//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFOLogDbEntities : DbContext
    {
        public SFOLogDbEntities()
            : base("name=SFOLogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SFOTblSystemLogCategory> SFOTblSystemLogCategory { get; set; }
        public virtual DbSet<SFOTblSystemLogProcess> SFOTblSystemLogProcess { get; set; }
        public virtual DbSet<SFOTblTransactionGenericLog> SFOTblTransactionGenericLog { get; set; }
        public virtual DbSet<SFOTblSystemModelConfig> SFOTblSystemModelConfig { get; set; }
        public virtual DbSet<SFOTblSystemModelConfig_Property> SFOTblSystemModelConfig_Property { get; set; }
        public virtual DbSet<SFOTblSystemModelConfig_PropertyQuery> SFOTblSystemModelConfig_PropertyQuery { get; set; }
        public virtual DbSet<TblSystemCustomerLocation_Audit_Log> TblSystemCustomerLocation_Audit_Log { get; set; }
    }
}
