//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    
    public partial class SFOOTCRequestResult
    {
        public System.Guid MasterActualJobHeader_Guid { get; set; }
        public string JobNumber { get; set; }
        public string Branch { get; set; }
        public System.Guid MasterCountry_Guid { get; set; }
        public string MasterCountryAbbreviation { get; set; }
        public string MachineID { get; set; }
        public int LockSeq { get; set; }
        public string MachineLockID { get; set; }
        public string SerialNumber { get; set; }
        public string ReferenceCode { get; set; }
        public string Dispatcher { get; set; }
        public Nullable<System.Guid> SFOSystemLockType_Guid { get; set; }
        public string LockTypeName { get; set; }
        public string LockMode { get; set; }
        public string LockStatus { get; set; }
        public string UserLockModeId { get; set; }
        public Nullable<System.Guid> MasterEmployee_Guid { get; set; }
        public string User { get; set; }
        public string PIN { get; set; }
        public string TouchKeyID { get; set; }
        public Nullable<System.Guid> MasterEmployee_Guid2 { get; set; }
        public string User2 { get; set; }
        public string PIN2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> TimeBlock { get; set; }
        public Nullable<System.Guid> SFOSystemOTCStatus_Guid { get; set; }
        public string OperationCode { get; set; }
    }
}
