//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblSystemModelConfig_Property
    {
        public System.Guid Guid { get; set; }
        public System.Guid SystemModelConfig_Guid { get; set; }
        public string PropertyNameSource { get; set; }
        public string PropertyNameTarget { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DatetimeModify { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModify { get; set; }
        public string LabelKey { get; set; }
        public Nullable<System.Guid> SystemModelConfig_PropertyQuery_Guid { get; set; }
        public Nullable<System.Guid> SystemLogCategory_Guid { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string OverwriteSystemMsgID { get; set; }
        public string OverwriteLabelIndex { get; set; }
    
        public virtual SFOTblSystemLogCategory SFOTblSystemLogCategory { get; set; }
        public virtual SFOTblSystemModelConfig SFOTblSystemModelConfig { get; set; }
        public virtual SFOTblSystemModelConfig_PropertyQuery SFOTblSystemModelConfig_PropertyQuery { get; set; }
    }
}
