//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblSystemMachineCapability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblSystemMachineCapability()
        {
            this.TblMasterActualJobHeader_Capability = new HashSet<TblMasterActualJobHeader_Capability>();
            this.TblSystemATMScreen = new HashSet<TblSystemATMScreen>();
            this.SFOTblMasterMachineModelType_Capability = new HashSet<SFOTblMasterMachineModelType_Capability>();
            this.TblMasterActualJobMCSItemSeal = new HashSet<TblMasterActualJobMCSItemSeal>();
            this.TblMasterCheckList = new HashSet<TblMasterCheckList>();
            this.SFOTblMasterMachineModelType_DefaultCassette = new HashSet<SFOTblMasterMachineModelType_DefaultCassette>();
        }
    
        public System.Guid Guid { get; set; }
        public string CapabilityDescription { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DatetimeModify { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModify { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControl_Guid { get; set; }
        public int CapabilityID { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobHeader_Capability> TblMasterActualJobHeader_Capability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSystemATMScreen> TblSystemATMScreen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType_Capability> SFOTblMasterMachineModelType_Capability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSItemSeal> TblMasterActualJobMCSItemSeal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCheckList> TblMasterCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType_DefaultCassette> SFOTblMasterMachineModelType_DefaultCassette { get; set; }
    }
}
