//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblTransactionServiceRequest_Solution
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public System.Guid SFOTransactionServiceRequest_Guid { get; set; }
        public System.Guid SFOMasterSolution_Guid { get; set; }
        public string SolutionID { get; set; }
        public string SolutionName { get; set; }
        public string SolutionDescription { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> SFOMasterProblem_Solution_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterProblem_Guid { get; set; }
        public string ProblemID { get; set; }
        public string ProblemName { get; set; }
        public Nullable<System.Guid> SFOMasterSubSolutionLevel1_Guid { get; set; }
        public string SFOMasterSubSolutionLevel1_ID { get; set; }
        public string SFOMasterSubSolutionLevel1_Name { get; set; }
        public Nullable<System.Guid> SFOMasterSubSolutionLevel2_Guid { get; set; }
        public string SFOMasterSubSolutionLevel2_ID { get; set; }
        public string SFOMasterSubSolutionLevel2_Name { get; set; }
        public Nullable<System.Guid> SFOMasterSubSolutionLevel3_Guid { get; set; }
        public string SFOMasterSubSolutionLevel3_ID { get; set; }
        public string SFOMasterSubSolutionLevel3_Name { get; set; }
        public Nullable<System.Guid> SFOMasterSubSolutionLevel4_Guid { get; set; }
        public string SFOMasterSubSolutionLevel4_ID { get; set; }
        public string SFOMasterSubSolutionLevel4_Name { get; set; }
    
        public virtual SFOTblMasterProblem SFOTblMasterProblem { get; set; }
        public virtual SFOTblMasterProblem_Solution SFOTblMasterProblem_Solution { get; set; }
        public virtual SFOTblMasterSolution SFOTblMasterSolution { get; set; }
        public virtual SFOTblTransactionServiceRequest SFOTblTransactionServiceRequest { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
