//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterEscalationHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterEscalationHeader()
        {
            this.SFOTblMasterEscalationDetail = new HashSet<SFOTblMasterEscalationDetail>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> SystemCustomerLocationType_Guid { get; set; }
        public Nullable<System.Guid> SFOSystemServiceRequestState_Guid { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string Configuration { get; set; }
        public string Content { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        public virtual TblSystemCustomerLocationType TblSystemCustomerLocationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterEscalationDetail> SFOTblMasterEscalationDetail { get; set; }
        public virtual SFOTblSystemServiceRequestState SFOTblSystemServiceRequestState { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
