//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachineModelType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterMachineModelType()
        {
            this.SFOTblMasterMachine = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterMachineModelType_Capability = new HashSet<SFOTblMasterMachineModelType_Capability>();
            this.SFOTblMasterMachineModelType_DefaultCassette = new HashSet<SFOTblMasterMachineModelType_DefaultCassette>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> SystemCustomerLocationType_Guid { get; set; }
        public string MachineModelTypeID { get; set; }
        public string MachineModelTypeName { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeModified { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        public virtual TblSystemCustomerLocationType TblSystemCustomerLocationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType_Capability> SFOTblMasterMachineModelType_Capability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType_DefaultCassette> SFOTblMasterMachineModelType_DefaultCassette { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
