//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblTransactionServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblTransactionServiceRequest()
        {
            this.SFOTblTransactionServiceRequest_Ecash = new HashSet<SFOTblTransactionServiceRequest_Ecash>();
            this.SFOTblTransactionServiceRequest_Journal = new HashSet<SFOTblTransactionServiceRequest_Journal>();
            this.SFOTblTransactionServiceRequest_Problem = new HashSet<SFOTblTransactionServiceRequest_Problem>();
            this.SFOTblTransactionServiceRequest_Solution = new HashSet<SFOTblTransactionServiceRequest_Solution>();
        }
    
        public System.Guid Guid { get; set; }
        public int DateStatus { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobHeader_Guid { get; set; }
        public System.Guid MasterCustomerLocation_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterCategory_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterServiceRequestType_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterPriority_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterSource_OpenSource_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterSource_CloseSource_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterReason_Guid { get; set; }
        public string TicketNumber { get; set; }
        public System.Guid TicketStatus_Guid { get; set; }
        public Nullable<System.DateTime> RequestedServiceDate { get; set; }
        public Nullable<System.DateTime> DateTimeOpened { get; set; }
        public Nullable<System.DateTime> DateTimeClosed { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string CustomerReferenceNumber { get; set; }
        public string ResponderReferenceNumber { get; set; }
        public string EscalationType { get; set; }
        public Nullable<int> EscalationLevel { get; set; }
        public Nullable<System.DateTime> EscalationTime { get; set; }
        public Nullable<System.DateTime> DateTimeNotified { get; set; }
        public string ReportedServiceRequestDescription { get; set; }
        public string eCashDenomination { get; set; }
        public Nullable<int> eCashAmount { get; set; }
        public string eCashCurrency { get; set; }
        public string TechMeetName { get; set; }
        public string TechMeetPhone { get; set; }
        public string TechMeetCompanyName { get; set; }
        public string TechMeetReasonID { get; set; }
        public string TechMeetSecurityRequired { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> FlagRescheduleRequest { get; set; }
        public Nullable<System.Guid> Reason_Guid { get; set; }
        public string ResolvedBy { get; set; }
        public string VendorSolutionID { get; set; }
        public Nullable<bool> FlagBillableIndicator { get; set; }
        public Nullable<System.DateTime> CalculatedDueDateTime { get; set; }
        public Nullable<bool> FlagNotifyNow { get; set; }
        public string Technician { get; set; }
        public Nullable<System.DateTime> DateTimeAcknowledged { get; set; }
        public Nullable<System.DateTime> DateTimeETA { get; set; }
        public Nullable<System.DateTime> DateTimeDepartureToOnsite { get; set; }
        public Nullable<System.DateTime> DateTimeReportedOnsite { get; set; }
        public Nullable<System.DateTime> DateTimeReportedResolved { get; set; }
        public Nullable<System.DateTime> DateTimeReportedDeparted { get; set; }
        public Nullable<System.DateTime> DateTimeReportedReturned { get; set; }
        public Nullable<System.DateTime> DateTimeDateTimeDown { get; set; }
        public Nullable<System.DateTime> DateTimeDispatched { get; set; }
        public Nullable<System.DateTime> DateTimeCustomerStart { get; set; }
        public Nullable<System.DateTime> DateTimeCustomerDispatched { get; set; }
        public Nullable<int> TotalPremiseTime { get; set; }
        public Nullable<System.Guid> MassServiceRequest_Guid { get; set; }
        public string PACNCode { get; set; }
        public Nullable<System.DateTime> DateTimeRequestedNotification { get; set; }
        public string CancellationReason { get; set; }
        public string CustomerCommentIn { get; set; }
        public string CustomerCommentOut { get; set; }
        public string CustomerNetworkID { get; set; }
        public string VendorNetworkID { get; set; }
        public string FileReference { get; set; }
        public string VendorCommentIn { get; set; }
        public string VendorCommentOut { get; set; }
        public string Owner { get; set; }
        public Nullable<System.Guid> OwnerSource_Guid { get; set; }
        public Nullable<bool> FlagClosedOnFirstContact { get; set; }
        public string BrinksLogNumber { get; set; }
        public Nullable<bool> FlagNonbillableToBranch { get; set; }
        public Nullable<bool> FlagNonbillableToCustomer { get; set; }
        public Nullable<bool> FlagSpecialCharges { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public Nullable<bool> FlagRescheduleApproved { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> TimeZoneLocal_Guid { get; set; }
        public Nullable<System.Guid> TimeZoneMachine_Guid { get; set; }
        public string BrinksNote { get; set; }
        public string ReasonName { get; set; }
        public Nullable<System.DateTime> DateTimeDueDate { get; set; }
        public Nullable<System.DateTime> DateTimeServiceDate { get; set; }
        public Nullable<bool> FlagStampDispatch { get; set; }
        public Nullable<bool> FlagStampAccept { get; set; }
        public Nullable<bool> FlagStampArrive { get; set; }
        public Nullable<bool> FlagStampRestore { get; set; }
        public Nullable<bool> FlagStampDepart { get; set; }
        public Nullable<bool> FlagStampReturn { get; set; }
        public string CancelReason { get; set; }
        public string ResponderName { get; set; }
        public Nullable<System.Guid> PreviousTicketStatus_Guid { get; set; }
        public Nullable<bool> flagTechMeetSecurityRequired { get; set; }
        public string ReportedDescription { get; set; }
        public Nullable<System.Guid> ParentTicketGuid { get; set; }
        public string OperationCode { get; set; }
        public Nullable<System.Guid> MasterDailyRunResource_Guid { get; set; }
        public string ResponderStatus { get; set; }
        public Nullable<bool> FlagStampReportedOnsite { get; set; }
        public Nullable<bool> FlagStampETA { get; set; }
        public Nullable<int> LockHour { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TimeBlock { get; set; }
        public string RescheduleReason { get; set; }
        public Nullable<bool> FlagCloseOTC { get; set; }
        public string ResponderEmail { get; set; }
        public string ResponderShift { get; set; }
        public Nullable<bool> FlagATM { get; set; }
        public Nullable<bool> FlagFLM { get; set; }
        public Nullable<bool> FlagCompuSafe { get; set; }
        public string MassRequestID { get; set; }
        public Nullable<bool> FlagEcash { get; set; }
        public Nullable<System.Guid> PreviousServiceRequestState_Guid { get; set; }
        public Nullable<bool> FlagPregenerate { get; set; }
        public Nullable<bool> FlagBilling { get; set; }
        public Nullable<bool> FlagBranchVendor { get; set; }
        public Nullable<int> EnvBranchTypeId { get; set; }
        public Nullable<System.Guid> SFOMasterMachineServiceType_Guid { get; set; }
        public Nullable<System.Guid> MasterReasonType_Guid { get; set; }
        public Nullable<bool> FlagOnHold { get; set; }
        public string ReferenceId { get; set; }
        public bool FlagNonCharge { get; set; }
        public bool FlagAllowRequestSLM { get; set; }
        public Nullable<System.DateTimeOffset> DateTimeTechMeet { get; set; }
        public Nullable<int> SFOSystemCloseType_ID { get; set; }
        public Nullable<System.DateTimeOffset> DateTimeTechnicianArrived { get; set; }
        public Nullable<System.DateTimeOffset> DateTimeTechnicianNotArrive { get; set; }
    
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblMasterReasonType TblMasterReasonType { get; set; }
        public virtual SFOTblMasterMachineServiceType SFOTblMasterMachineServiceType { get; set; }
        public virtual SFOTblMasterSource SFOTblMasterSource { get; set; }
        public virtual SFOTblMasterSource SFOTblMasterSource1 { get; set; }
        public virtual SFOTblSystemServiceRequestState SFOTblSystemServiceRequestState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Ecash> SFOTblTransactionServiceRequest_Ecash { get; set; }
        public virtual SFOTblTransactionServiceRequest_Info SFOTblTransactionServiceRequest_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Journal> SFOTblTransactionServiceRequest_Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Problem> SFOTblTransactionServiceRequest_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Solution> SFOTblTransactionServiceRequest_Solution { get; set; }
        public virtual TblMasterActualJobHeader TblMasterActualJobHeader { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
