//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachineModelType_DefaultCassette
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> SFOMasterMachineModelType_Guid { get; set; }
        public Nullable<System.Guid> SFOSystemMachineCapability_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterCassette_Guid { get; set; }
        public Nullable<System.Guid> MasterCurrency_Guid { get; set; }
        public int Sequence { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        public virtual SFOTblMasterCassette SFOTblMasterCassette { get; set; }
        public virtual SFOTblMasterMachineModelType SFOTblMasterMachineModelType { get; set; }
        public virtual SFOTblSystemMachineCapability SFOTblSystemMachineCapability { get; set; }
    }
}
