//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblSystemServiceRequestState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblSystemServiceRequestState()
        {
            this.SFOTblMasterEscalationHeader = new HashSet<SFOTblMasterEscalationHeader>();
            this.SFOTblSystemEscalationRuleHeader = new HashSet<SFOTblSystemEscalationRuleHeader>();
            this.SFOTblTransactionServiceRequest = new HashSet<SFOTblTransactionServiceRequest>();
        }
    
        public System.Guid Guid { get; set; }
        public string ServiceRequestStateCode { get; set; }
        public string ServiceRequestStateName { get; set; }
        public string NextServiceRequestStateName { get; set; }
        public string NextServiceRequestStateCode { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagNotify { get; set; }
        public Nullable<bool> FlagEscalation { get; set; }
        public Nullable<int> StateIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterEscalationHeader> SFOTblMasterEscalationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemEscalationRuleHeader> SFOTblSystemEscalationRuleHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest> SFOTblTransactionServiceRequest { get; set; }
    }
}
