//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachine_AssociatedMachine
    {
        public System.Guid Guid { get; set; }
        public System.Guid SFOMasterMachine_Guid { get; set; }
        public System.Guid SFOMasterAssociatedMachine_Guid { get; set; }
    
        public virtual SFOTblMasterMachine SFOTblMasterMachine { get; set; }
        public virtual SFOTblMasterMachine SFOTblMasterMachine1 { get; set; }
    }
}
