//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblTransactionServiceRequest_Ecash
    {
        public System.Guid Guid { get; set; }
        public System.Guid SFOTransactionServiceRequest_Guid { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Currency { get; set; }
        public string Denomination { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<double> DenominationValue { get; set; }
        public Nullable<int> DenominationQuantity { get; set; }
        public Nullable<int> Unit { get; set; }
    
        public virtual SFOTblTransactionServiceRequest SFOTblTransactionServiceRequest { get; set; }
    }
}
