//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachineModelType_Capability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterMachineModelType_Capability()
        {
            this.SFOTblMasterMachine_Capabilties = new HashSet<SFOTblMasterMachine_Capabilties>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterMachineModelType_Guid { get; set; }
        public System.Guid SystemMachineCapability_Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_Capabilties> SFOTblMasterMachine_Capabilties { get; set; }
        public virtual SFOTblMasterMachineModelType SFOTblMasterMachineModelType { get; set; }
        public virtual SFOTblSystemMachineCapability SFOTblSystemMachineCapability { get; set; }
    }
}
