//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachineServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterMachineServiceType()
        {
            this.SFOTblMasterMachine = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterProblem = new HashSet<SFOTblMasterProblem>();
            this.SFOTblTransactionServiceRequest_Problem = new HashSet<SFOTblTransactionServiceRequest_Problem>();
            this.SFOTblTransactionServiceRequest = new HashSet<SFOTblTransactionServiceRequest>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public string MachineServiceTypeID { get; set; }
        public string MachineServiceTypeName { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeModified { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterProblem> SFOTblMasterProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Problem> SFOTblTransactionServiceRequest_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest> SFOTblTransactionServiceRequest { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
