//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblSystemModelConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblSystemModelConfig()
        {
            this.SFOTblSystemLogCategory = new HashSet<SFOTblSystemLogCategory>();
            this.SFOTblSystemModelConfig_Property = new HashSet<SFOTblSystemModelConfig_Property>();
        }
    
        public System.Guid Guid { get; set; }
        public string ConfigKey { get; set; }
        public string ModelNameSource { get; set; }
        public string ModelNameTarget { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DatetimeModify { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModify { get; set; }
        public string DefaultSystemMsgID { get; set; }
        public string DefaultLabelIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemLogCategory> SFOTblSystemLogCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemModelConfig_Property> SFOTblSystemModelConfig_Property { get; set; }
    }
}
