//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterProblem_Solution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterProblem_Solution()
        {
            this.SFOTblTransactionServiceRequest_Solution = new HashSet<SFOTblTransactionServiceRequest_Solution>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public System.Guid SFOMasterProblem_Guid { get; set; }
        public System.Guid SFOMasterSolution_Guid { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeModified { get; set; }
    
        public virtual SFOTblMasterProblem SFOTblMasterProblem { get; set; }
        public virtual SFOTblMasterSolution SFOTblMasterSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Solution> SFOTblTransactionServiceRequest_Solution { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
