//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterMachine()
        {
            this.SFOTblMasterMachine_Capabilties = new HashSet<SFOTblMasterMachine_Capabilties>();
            this.SFOTblMasterMachine_AssociatedMachine = new HashSet<SFOTblMasterMachine_AssociatedMachine>();
            this.SFOTblMasterMachine_AssociatedMachine1 = new HashSet<SFOTblMasterMachine_AssociatedMachine>();
            this.SFOTblMasterMachine_Cassette = new HashSet<SFOTblMasterMachine_Cassette>();
            this.SFOTblMasterMachine_ECash = new HashSet<SFOTblMasterMachine_ECash>();
            this.SFOTblMasterMachine_LockType = new HashSet<SFOTblMasterMachine_LockType>();
        }
    
        public System.Guid Guid { get; set; }
        public string MachineID { get; set; }
        public string CustomerMachineID { get; set; }
        public string VendorMachineID { get; set; }
        public Nullable<System.Guid> SFOMasterMachineServiceType_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterMachineSubServiceType_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterMachineModelType_Guid { get; set; }
        public Nullable<System.Guid> SystemCustomerLocationType_Guid { get; set; }
        public Nullable<System.Guid> MasterVendor_Guid { get; set; }
        public string ServiceCode { get; set; }
        public bool FlagDailyCreditIndicator { get; set; }
        public Nullable<bool> FlagRemoteSafeManagementIndicator { get; set; }
        public Nullable<bool> FlagDeviceDashBoardIndicator { get; set; }
        public string SerialNumber { get; set; }
        public string AccountReceivable { get; set; }
        public string MachineEDI { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> SFOMasterCountryTimeZone_Guid { get; set; }
        public Nullable<int> FLMSLATime { get; set; }
        public Nullable<int> ECashSLATime { get; set; }
        public Nullable<int> CompuSafeSLATime { get; set; }
        public Nullable<System.Guid> SFOMasterECashType_Guid { get; set; }
        public string SafeSerialNumber { get; set; }
        public Nullable<System.Guid> SFOMasterMachineBrand_Guid { get; set; }
        public string LockSerialNumber { get; set; }
        public Nullable<System.Guid> SFOSystemLockType_Guid { get; set; }
        public Nullable<System.Guid> SFOServicingBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOAssignedBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOFLMBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOArmoredBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOCashBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterFLMZone_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterECashZone_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterCompuSafeZone_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterBillingType_Guid { get; set; }
        public string Run { get; set; }
        public bool FlagEcash { get; set; }
        public string Address2 { get; set; }
        public string CombinationCode { get; set; }
        public Nullable<bool> FlagNoneLock { get; set; }
        public Nullable<System.Guid> SFOMasterAlarmSystem_Guid { get; set; }
        public string MonitoringNetwork { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string MachineReason { get; set; }
        public bool FlagSuspension { get; set; }
        public Nullable<System.Guid> SFOTblMasterMonitoringNetwork_Guid { get; set; }
        public Nullable<System.Guid> SystemMachineOwner_Guid { get; set; }
        public Nullable<System.Guid> SystemMachineType_Guid { get; set; }
        public Nullable<int> MaximumCassettes { get; set; }
        public Nullable<System.Guid> SystemATMDistance_Guid { get; set; }
        public Nullable<System.Guid> SystemGlobalUnit_Guid { get; set; }
        public Nullable<decimal> DistanceSiteToMachine { get; set; }
        public Nullable<decimal> TotalATM { get; set; }
        public Nullable<decimal> TotalAmountStay { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblSystemCustomerLocationType TblSystemCustomerLocationType { get; set; }
        public virtual TblSystemCustomerLocationType TblSystemCustomerLocationType1 { get; set; }
        public virtual SFOTblMasterCountryTimeZone SFOTblMasterCountryTimeZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_Capabilties> SFOTblMasterMachine_Capabilties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_AssociatedMachine> SFOTblMasterMachine_AssociatedMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_AssociatedMachine> SFOTblMasterMachine_AssociatedMachine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_Cassette> SFOTblMasterMachine_Cassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_ECash> SFOTblMasterMachine_ECash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_LockType> SFOTblMasterMachine_LockType { get; set; }
        public virtual SFOTblMasterMachineModelType SFOTblMasterMachineModelType { get; set; }
        public virtual SFOTblMasterMachineServiceType SFOTblMasterMachineServiceType { get; set; }
        public virtual SFOTblSystemLockType SFOTblSystemLockType { get; set; }
        public virtual SFOTblMasterMonitoringNetwork SFOTblMasterMonitoringNetwork { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
        public virtual TblMasterSite TblMasterSite1 { get; set; }
        public virtual TblMasterSite TblMasterSite2 { get; set; }
        public virtual TblMasterSite TblMasterSite3 { get; set; }
        public virtual TblMasterSite TblMasterSite4 { get; set; }
    }
}
