//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterCountryTimeZone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterCountryTimeZone()
        {
            this.TblMasterCustomerLocation = new HashSet<TblMasterCustomerLocation>();
            this.SFOTblMasterMachine = new HashSet<SFOTblMasterMachine>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCountry_Guid { get; set; }
        public System.Guid SystemTimeZone_Guid { get; set; }
        public string CountryTimeZoneID { get; set; }
        public Nullable<System.DateTime> PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDateTimeModified { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation> TblMasterCustomerLocation { get; set; }
        public virtual TblSystemTimezone TblSystemTimezone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine { get; set; }
    }
}
