//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterCassette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblMasterCassette()
        {
            this.SFOTblMasterMachine_Cassette = new HashSet<SFOTblMasterMachine_Cassette>();
            this.TblMasterActualJobMCSBulkDepositReportEntry = new HashSet<TblMasterActualJobMCSBulkDepositReportEntry>();
            this.SFOTblMasterMachineModelType_DefaultCassette = new HashSet<SFOTblMasterMachineModelType_DefaultCassette>();
        }
    
        public System.Guid Guid { get; set; }
        public string CassetteName { get; set; }
        public System.Guid TblSystemCassetteType_Guid { get; set; }
        public int MaximumCapacity { get; set; }
        public int OptimumCapacity { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public System.Guid TblMasterCountry_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        public virtual TblSystemCassetteType TblSystemCassetteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_Cassette> SFOTblMasterMachine_Cassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkDepositReportEntry> TblMasterActualJobMCSBulkDepositReportEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType_DefaultCassette> SFOTblMasterMachineModelType_DefaultCassette { get; set; }
    }
}
