//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblTransactionServiceRequest_Info
    {
        public System.Guid TransactionServiceRequest_Guid { get; set; }
        public string SiteID { get; set; }
        public string MachineID { get; set; }
        public string SerialNumber { get; set; }
        public string CustomerName { get; set; }
        public string MachineType { get; set; }
        public string MachineBrand { get; set; }
        public string MachineModel { get; set; }
        public string ServiceType { get; set; }
        public string ServiceSubType { get; set; }
        public string LockType { get; set; }
        public string MachinePhone { get; set; }
        public string DistrictRegion { get; set; }
        public string SiteAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string ServicingBranch { get; set; }
        public string AssignedBranch { get; set; }
        public string FLMBranch { get; set; }
        public string AmoredBranch { get; set; }
        public bool FlagDailyCredit { get; set; }
        public bool FlagRemoteSafeManagement { get; set; }
        public bool FlagDeviceDashboard { get; set; }
        public string FLMZone { get; set; }
        public string ECashZone { get; set; }
        public string Run { get; set; }
        public string BillingType { get; set; }
        public string ContractHours { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DatetimeModify { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModify { get; set; }
        public Nullable<int> SLATime { get; set; }
        public string SFOMasterCountryTimeZone_Code { get; set; }
        public Nullable<int> MachineTimeZoneID { get; set; }
        public Nullable<System.Guid> BrinksLocationGuid { get; set; }
        public string ECashSetup { get; set; }
        public Nullable<System.Guid> LockType_Guid { get; set; }
        public Nullable<System.Guid> Machine_Guid { get; set; }
        public Nullable<System.Guid> MachineType_Guid { get; set; }
        public string MachineBrinksSiteCode { get; set; }
        public Nullable<System.Guid> MachineBrinksSite_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterCountryTimeZone_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public Nullable<bool> FlagSupportsDaylightSavingTime { get; set; }
        public string CombinationCode { get; set; }
        public string LockTypeReferenceCode { get; set; }
        public Nullable<System.Guid> MachineCountryGuid { get; set; }
        public string MachineRemark { get; set; }
        public string MachineName { get; set; }
        public Nullable<bool> FlagRequirePACN { get; set; }
        public Nullable<int> CustomerSLATime { get; set; }
        public Nullable<System.Guid> ServiceBranchGuid { get; set; }
        public Nullable<bool> FlagIntegrationServiceBranch { get; set; }
        public Nullable<System.Guid> FLMBranchGuid { get; set; }
        public Nullable<bool> FlagIntegrationFLMBranch { get; set; }
        public string AlarmCode { get; set; }
        public bool FlagAllowSafeAccess { get; set; }
        public Nullable<int> SLATime2 { get; set; }
    
        public virtual SFOTblTransactionServiceRequest SFOTblTransactionServiceRequest { get; set; }
    }
}
