//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblSystemLogCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFOTblSystemLogCategory()
        {
            this.TblMasterRouteTransactionLog = new HashSet<TblMasterRouteTransactionLog>();
            this.SFOTblTransactionGenericLog = new HashSet<SFOTblTransactionGenericLog>();
            this.SFOTblSystemModelConfig_Property = new HashSet<SFOTblSystemModelConfig_Property>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid SystemModelConfig_Guid { get; set; }
        public System.Guid SystemLogProcess_Guid { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<int> SeqIndexShow { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual SFOTblSystemLogProcess SFOTblSystemLogProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterRouteTransactionLog> TblMasterRouteTransactionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionGenericLog> SFOTblTransactionGenericLog { get; set; }
        public virtual SFOTblSystemModelConfig SFOTblSystemModelConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemModelConfig_Property> SFOTblSystemModelConfig_Property { get; set; }
    }
}
