//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFOTblMasterMachine_LockType
    {
        public System.Guid Guid { get; set; }
        public System.Guid SFOMasterMachine_Guid { get; set; }
        public System.Guid SFOSystemLockType_Guid { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string CombinationCode { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<int> LockSeq { get; set; }
        public string SerailNumber { get; set; }
        public string MachineLockID { get; set; }
        public Nullable<System.Guid> SFOSystemUserLockMode_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual SFOTblMasterMachine SFOTblMasterMachine { get; set; }
        public virtual SFOTblSystemLockType SFOTblSystemLockType { get; set; }
    }
}
