//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBankCleanOutJobDelivery_Temp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBankCleanOutJobDelivery_Temp()
        {
            this.TblBankCleanOutJobDelivery_NonbarCodeTemp = new HashSet<TblBankCleanOutJobDelivery_NonbarCodeTemp>();
            this.TblBankCleanOutJobDelivery_SealTemp = new HashSet<TblBankCleanOutJobDelivery_SealTemp>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterRouteGroupDetail_Guid { get; set; }
        public Nullable<System.Guid> MasterRoute_Guid { get; set; }
        public Nullable<System.Guid> MasterRouteJobHeader_Guid { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public Nullable<System.Guid> PickupAcutalJobGuid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> InternalDepartment_Guid { get; set; }
        public Nullable<System.Guid> MasterDailyRunResource_Guid { get; set; }
        public string LocationName { get; set; }
        public string LocationCode { get; set; }
        public string MasterRouteName { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> STC { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public string CommodityCode { get; set; }
        public Nullable<System.DateTime> SchduleTime { get; set; }
        public Nullable<System.DateTime> DatePickupInternalDeptForBCD { get; set; }
        public Nullable<System.Guid> PreVaultGuid { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
        public bool FlagCommodityHaveDetail { get; set; }
        public System.Guid SystemMaterRouteTypeOfWeek_Guid { get; set; }
        public Nullable<System.Guid> SystemLineOfBusiness_Guid { get; set; }
        public Nullable<System.DateTime> DefaultDesiredDeliveryDate { get; set; }
        public Nullable<System.DateTime> DesiredDeliveryDate { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.Guid> SystemTripIndicator_Guid { get; set; }
        public bool FlagBCDMultiBr { get; set; }
        public Nullable<System.Guid> MasterSitePathHeader_Guid { get; set; }
        public string MasterDayOfWeek_Name { get; set; }
        public Nullable<System.Guid> MasterCustomerContract_Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBankCleanOutJobDelivery_NonbarCodeTemp> TblBankCleanOutJobDelivery_NonbarCodeTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBankCleanOutJobDelivery_SealTemp> TblBankCleanOutJobDelivery_SealTemp { get; set; }
        public virtual TblMasterSitePathHeader TblMasterSitePathHeader { get; set; }
        public virtual TblSystemMaterRouteTypeOfWeek TblSystemMaterRouteTypeOfWeek { get; set; }
    }
}
