//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBankCleanOutJobDelivery_NonbarCodeTemp
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> BankCleanOutJobDelivery_Temp_Guid { get; set; }
        public Nullable<System.Guid> MasterCurrency_Guid { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> PN { get; set; }
        public Nullable<int> NK { get; set; }
        public Nullable<int> DM { get; set; }
        public Nullable<int> QT { get; set; }
        public Nullable<int> LN { get; set; }
        public Nullable<int> TN { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
    
        public virtual TblBankCleanOutJobDelivery_Temp TblBankCleanOutJobDelivery_Temp { get; set; }
    }
}
