//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChargeCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblChargeCategory()
        {
            this.TblChargeCategory_Action = new HashSet<TblChargeCategory_Action>();
            this.TblChargeCategory_Rule = new HashSet<TblChargeCategory_Rule>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid PricingRule_Guid { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public bool IsVoid { get; set; }
        public System.Guid MasterRevenueCategory_Guid { get; set; }
        public System.Guid SystemPricingChargeType_Guid { get; set; }
        public int SeqNo { get; set; }
        public System.Guid SystemPricingSatisfy_Guid { get; set; }
        public System.Guid SystemPricingCriteria_Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChargeCategory_Action> TblChargeCategory_Action { get; set; }
        public virtual TblPricingRule TblPricingRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChargeCategory_Rule> TblChargeCategory_Rule { get; set; }
    }
}
