//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChargeCategory_Rule_Value
    {
        public System.Guid Guid { get; set; }
        public System.Guid ChargeCategory_Rule_Guid { get; set; }
        public string Value { get; set; }
        public int SeqNo { get; set; }
    
        public virtual TblChargeCategory_Rule TblChargeCategory_Rule { get; set; }
    }
}
