//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChargeCategory_Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblChargeCategory_Action()
        {
            this.TblChargeCategory_Action_Charge = new HashSet<TblChargeCategory_Action_Charge>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid ChargeCategory_Guid { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public System.Guid BasisPricingVariable_Guid { get; set; }
        public string Value { get; set; }
        public int SeqNo { get; set; }
        public bool IsVoid { get; set; }
        public bool IsProgressive { get; set; }
        public Nullable<System.Guid> SystemPricingCriteria_Guid { get; set; }
        public Nullable<System.Guid> SystemPricingVariable_Guid { get; set; }
    
        public virtual TblChargeCategory TblChargeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChargeCategory_Action_Charge> TblChargeCategory_Action_Charge { get; set; }
    }
}
