//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChargeCategory_Action_Charge_Condition
    {
        public System.Guid Guid { get; set; }
        public System.Guid ChargeCategory_Action_Charge_Guid { get; set; }
        public int SeqNo { get; set; }
        public Nullable<System.Guid> SystemPricingVariable_Guid { get; set; }
        public Nullable<System.Guid> SystemOperator_Guid { get; set; }
        public string Value { get; set; }
    
        public virtual TblChargeCategory_Action_Charge TblChargeCategory_Action_Charge { get; set; }
    }
}
