//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChargeCategory_Action_Charge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblChargeCategory_Action_Charge()
        {
            this.TblChargeCategory_Action_Charge_Condition = new HashSet<TblChargeCategory_Action_Charge_Condition>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid ChargeCategory_Action_Guid { get; set; }
        public int SeqNo { get; set; }
        public System.Guid BasisPricingVariable_Guid { get; set; }
        public Nullable<decimal> QuantityOfBasis { get; set; }
        public Nullable<System.Guid> SystemLogicalOperator_Guid { get; set; }
        public System.Guid SystemOperator_Guid { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public bool IsVoid { get; set; }
        public Nullable<System.Guid> SystemDivisionRounding_Guid { get; set; }
        public Nullable<System.Guid> SystemPricingVariable_Guid { get; set; }
        public bool FlagForEvery { get; set; }
        public string SQLStatement { get; set; }
    
        public virtual TblChargeCategory_Action TblChargeCategory_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChargeCategory_Action_Charge_Condition> TblChargeCategory_Action_Charge_Condition { get; set; }
    }
}
