//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashProduct_ProductAttribute_Limit_Values
    {
        public System.Guid Guid { get; set; }
        public System.Guid LeedToCashProduct_ProductAttribute_Guid { get; set; }
        public System.Guid MasterCurrency_Guid { get; set; }
        public decimal PerItem { get; set; }
        public decimal PerJob { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
    
        public virtual TblLeedToCashProduct_ProductAttribute TblLeedToCashProduct_ProductAttribute { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
    }
}
