//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashQuotation_Clause
    {
        public System.Guid Guid { get; set; }
        public string ProductId { get; set; }
        public System.Guid LeedToCashQuotation_Guid { get; set; }
        public string ClauseID { get; set; }
        public string ClauseName { get; set; }
        public string ClauseCategoryName { get; set; }
        public string ClauseDescription { get; set; }
        public Nullable<bool> FlagMandatory { get; set; }
        public Nullable<bool> FlagInherit { get; set; }
        public Nullable<bool> FlagEditableInContract { get; set; }
        public Nullable<bool> FlagVisibleInContract { get; set; }
        public Nullable<bool> FlagVisibleInQuotation { get; set; }
        public Nullable<int> ClauseSeqNo { get; set; }
        public Nullable<System.Guid> MasterClause_Guid { get; set; }
        public Nullable<System.Guid> MasterClauseCat_Guid { get; set; }
        public string ClauseDetail { get; set; }
        public string ClauseDetailFieldID { get; set; }
        public Nullable<System.Guid> LeadToCashQuotation_Bid_Product_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashQuotation_Product_Guid { get; set; }
    
        public virtual TblLeedToCashQuotation TblLeedToCashQuotation { get; set; }
        public virtual TblLeedToCashQuotation_Product TblLeedToCashQuotation_Product { get; set; }
    }
}
