//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashQuotation_ProductAttribute
    {
        public System.Guid Guid { get; set; }
        public System.Guid LeedToCashQuotation_Guid { get; set; }
        public string ProductId { get; set; }
        public System.Guid LeedToCashProduct_ProductAttribute_Guid { get; set; }
        public Nullable<System.Guid> LeadToCashQuotation_Bid_Product_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashQuotation_Product_Guid { get; set; }
    
        public virtual TblLeedToCashProduct_ProductAttribute TblLeedToCashProduct_ProductAttribute { get; set; }
        public virtual TblLeedToCashQuotation TblLeedToCashQuotation { get; set; }
        public virtual TblLeedToCashQuotation_Product TblLeedToCashQuotation_Product { get; set; }
    }
}
