//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashMasterClauseScope
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblLeedToCashMasterClauseScope()
        {
            this.TblLeedToCashMasterClauseScopeDetail = new HashSet<TblLeedToCashMasterClauseScopeDetail>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterClause_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashClauseScopeType_Guid { get; set; }
        public bool FlagMandatory { get; set; }
        public bool FlagEdiable { get; set; }
    
        public virtual TblLeedToCashMasterClause TblLeedToCashMasterClause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashMasterClauseScopeDetail> TblLeedToCashMasterClauseScopeDetail { get; set; }
    }
}
