//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashQuotation_PricingRule_Mapping
    {
        public System.Guid Guid { get; set; }
        public System.Guid LeedToCashQuotation_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashProduct_PricingRule_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashProduct_PricingRule_Source_Guid { get; set; }
        public bool FlagExcess { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductServiceType { get; set; }
        public string LOBName { get; set; }
        public Nullable<bool> FlagRateChanged { get; set; }
        public Nullable<System.Guid> LeadToCashQuotation_Bid_Product_Guid { get; set; }
        public bool FlagApproved { get; set; }
        public Nullable<System.Guid> LeedToCashQuotation_Product_Guid { get; set; }
        public Nullable<decimal> AdjustedAmount { get; set; }
        public string AdjustedTypeText { get; set; }
        public bool IsExistInContract { get; set; }
        public Nullable<System.Guid> PricingRule_Guid { get; set; }
        public Nullable<System.Guid> PricingRuleSource_Guid { get; set; }
    
        public virtual TblLeedToCashQuotation TblLeedToCashQuotation { get; set; }
        public virtual TblLeedToCashQuotation_Product TblLeedToCashQuotation_Product { get; set; }
        public virtual TblPricingRule TblPricingRule { get; set; }
        public virtual TblPricingRule TblPricingRuleSource { get; set; }
    }
}
