//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashProduct_Clause
    {
        public System.Guid Guid { get; set; }
        public System.Guid LeedToCashProduct_Guid { get; set; }
        public System.Guid LeedToCashMasterClause_Guid { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<bool> FlagInherit { get; set; }
        public bool FlagVisibleInContract { get; set; }
        public bool FlagVisibleInQuotation { get; set; }
        public bool FlagMandatory { get; set; }
    
        public virtual TblLeedToCashMasterClause TblLeedToCashMasterClause { get; set; }
        public virtual TblLeedToCashProduct TblLeedToCashProduct { get; set; }
    }
}
