//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashProduct_ProductAttribute_ServiceWindows
    {
        public System.Guid Guid { get; set; }
        public System.Guid LeedToCashProduct_ProductAttribute_Guid { get; set; }
        public System.Guid SystemDayOfWeek_Guid { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual TblLeedToCashProduct_ProductAttribute TblLeedToCashProduct_ProductAttribute { get; set; }
    }
}
