//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLeedToCashContract_PricingRules
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomerContract_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashProduct_PricingRule_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashProduct_PricingRule_Source_Guid { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductServiceType { get; set; }
        public string LOBName { get; set; }
        public Nullable<System.Guid> LeadToCashContractAddendumDetail_Guid { get; set; }
        public Nullable<System.Guid> PricingRule_Guid { get; set; }
        public Nullable<System.Guid> PricingRuleSource_Guid { get; set; }
    
        public virtual TblMasterCustomerContract TblMasterCustomerContract { get; set; }
        public virtual TblPricingRule TblPricingRule { get; set; }
        public virtual TblPricingRule TblPricingRule1 { get; set; }
    }
}
