//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobMCSRecyclingMachineReportEntry
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterActualJobMCSRecyclingMachineReport_Guid { get; set; }
        public System.Guid MasterCurrency_Guid { get; set; }
        public string CurrencyAbbr { get; set; }
        public System.Guid MasterDenomination_Guid { get; set; }
        public decimal DenominationValue { get; set; }
        public int Remain { get; set; }
        public int Reject { get; set; }
        public decimal Amount { get; set; }
        public int CassetteSequence { get; set; }
    
        public virtual TblMasterActualJobMCSRecyclingMachineReport TblMasterActualJobMCSRecyclingMachineReport { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        public virtual TblMasterDenomination TblMasterDenomination { get; set; }
    }
}
