//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterGroup_MenuCommand
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterGroup_Guid { get; set; }
        public Nullable<System.Guid> MasterMenuDetailCommand_Guid { get; set; }
    
        public virtual TblMasterGroup TblMasterGroup { get; set; }
        public virtual TblMasterMenuDetailCommand TblMasterMenuDetailCommand { get; set; }
    }
}
