//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterSalesTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterSalesTeam()
        {
            this.TblMasterSalesTeamCustomerMapping = new HashSet<TblMasterSalesTeamCustomerMapping>();
            this.TblMasterSalesTeamUserMapping = new HashSet<TblMasterSalesTeamUserMapping>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCountry_Guid { get; set; }
        public string TeamName { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DatetimeModify { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModify { get; set; }
        public string TeamCode { get; set; }
        public bool FlagDisable { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSalesTeamCustomerMapping> TblMasterSalesTeamCustomerMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSalesTeamUserMapping> TblMasterSalesTeamUserMapping { get; set; }
    }
}
