//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCurrency_ExchangeRate
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterCurrencySource_Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public System.Guid MasterCurrencyTarget_Guid { get; set; }
        public decimal ExchangeRate { get; set; }
        public string Source { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency1 { get; set; }
    }
}
