//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobItemsLiability_Denomination
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobItemsLiability_Guid { get; set; }
        public Nullable<System.Guid> MasterDenomination_Guid { get; set; }
        public Nullable<System.Guid> SystemDenominationUnit_Guid { get; set; }
        public Nullable<int> Qty { get; set; }
        public double DenominationValue { get; set; }
        public Nullable<double> Value { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string DenominationText { get; set; }
    }
}
