//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCustomer()
        {
            this.TblLeedToCashProduct = new HashSet<TblLeedToCashProduct>();
            this.TblLeedToCashQuotation = new HashSet<TblLeedToCashQuotation>();
            this.TblLeedToCashQuotation1 = new HashSet<TblLeedToCashQuotation>();
            this.TblLeedToCashQuotation_Customer_Mapping = new HashSet<TblLeedToCashQuotation_Customer_Mapping>();
            this.TblMasterCustomer_Account = new HashSet<TblMasterCustomer_Account>();
            this.TblMasterCustomerContract = new HashSet<TblMasterCustomerContract>();
            this.TblMasterCustomerContract1 = new HashSet<TblMasterCustomerContract>();
            this.TblMasterSalesTeamCustomerMapping = new HashSet<TblMasterSalesTeamCustomerMapping>();
            this.TblMasterSubLob = new HashSet<TblMasterSubLob>();
            this.TblMasterCustomer_Account1 = new HashSet<TblMasterCustomer_Account>();
            this.TblMasterCustomer_JobHideScreen = new HashSet<TblMasterCustomer_JobHideScreen>();
            this.TblVaultBalance_Discrepancy = new HashSet<TblVaultBalance_Discrepancy>();
            this.TblVaultBalance_Discrepancy1 = new HashSet<TblVaultBalance_Discrepancy>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> GlobalMasterCustomer_Guid { get; set; }
        public string CustomerCodeExternalReference { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public Nullable<System.Guid> MasterCity_Guid { get; set; }
        public string StateName { get; set; }
        public Nullable<System.Guid> MasterDistrict_Guid { get; set; }
        public string CitryName { get; set; }
        public string PrefixReferenceCodeATMID { get; set; }
        public Nullable<System.Guid> SystemCustomerOfType_Guid { get; set; }
        public Nullable<System.Guid> MasterServiceHour_Guid { get; set; }
        public string CustomerFullName { get; set; }
        public string CustomerSystemName { get; set; }
        public string CustomerAbbrevaitionName { get; set; }
        public string CustomerReportName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerEmail { get; set; }
        public string AirclicReferenceCode { get; set; }
        public string PostelCode { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public Nullable<bool> Flag3Party { get; set; }
        public Nullable<bool> FlagChkInventory { get; set; }
        public Nullable<bool> FlagExchangeFund { get; set; }
        public Nullable<bool> FlagRequiredtoInputSTC { get; set; }
        public Nullable<bool> FlagEmailApplyAll { get; set; }
        public Nullable<bool> FlagChkTransactionFromPickupDate { get; set; }
        public Nullable<bool> FlagChkCustomer { get; set; }
        public Nullable<bool> FlagATMCustomer { get; set; }
        public Nullable<int> SlaTime { get; set; }
        public string LogoImage { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagDefaultSystem { get; set; }
        public Nullable<System.Guid> MasterCountry_State_Guid { get; set; }
        public Nullable<bool> FlagSendSignature { get; set; }
        public string PwdSignatureList { get; set; }
        public string TaxID { get; set; }
        public string CommercialRegistrationID { get; set; }
        public string PdfPassword { get; set; }
        public string ExtCommercialName { get; set; }
        public Nullable<System.DateTime> StartServiceDate { get; set; }
        public Nullable<System.DateTime> EndServiceDate { get; set; }
        public Nullable<System.Guid> MasterClassCustomer_Guid { get; set; }
        public string TermConditionBody { get; set; }
        public bool FlagSftp_POD { get; set; }
        public string Path_Sftp { get; set; }
        public string Username_Sftp { get; set; }
        public string Password_Sftp { get; set; }
        public Nullable<int> Port_Sftp { get; set; }
        public string SecondTaxID { get; set; }
        public Nullable<System.Guid> DirectClass_Guid { get; set; }
        public Nullable<System.Guid> SubClass_Guid { get; set; }
        public bool FlagGenUnableToServiceReport { get; set; }
        public string SftpPublicKey { get; set; }
        public Nullable<int> SystemSFTPLogInTypeID { get; set; }
        public Nullable<System.DateTime> LastNemoSync { get; set; }
        public string ReferenceId { get; set; }
        public bool FlagShowLayoutSealOnly { get; set; }
        public decimal PavementLimit { get; set; }
        public Nullable<System.Guid> PavementLimitCurrency_Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct> TblLeedToCashProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation> TblLeedToCashQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation> TblLeedToCashQuotation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation_Customer_Mapping> TblLeedToCashQuotation_Customer_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomer_Account> TblMasterCustomer_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerContract> TblMasterCustomerContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerContract> TblMasterCustomerContract1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSalesTeamCustomerMapping> TblMasterSalesTeamCustomerMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSubLob> TblMasterSubLob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomer_Account> TblMasterCustomer_Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomer_JobHideScreen> TblMasterCustomer_JobHideScreen { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy1 { get; set; }
    }
}
