//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCustomerLocation()
        {
            this.TblLeedToCashQuotation_Location_Mapping = new HashSet<TblLeedToCashQuotation_Location_Mapping>();
            this.TblMasterCustomerContract_ServiceLocation = new HashSet<TblMasterCustomerContract_ServiceLocation>();
            this.SFOTblTransactionServiceRequest = new HashSet<SFOTblTransactionServiceRequest>();
            this.TblMasterCustomerLocation_BrinksSite = new HashSet<TblMasterCustomerLocation_BrinksSite>();
            this.TblMasterCustomerLocation_LocationDestination = new HashSet<TblMasterCustomerLocation_LocationDestination>();
            this.TblMasterCustomerLocation_LocationDestination1 = new HashSet<TblMasterCustomerLocation_LocationDestination>();
            this.TblMasterCustomerLocation_ServiceHour = new HashSet<TblMasterCustomerLocation_ServiceHour>();
            this.TblMasterSitePathDestination = new HashSet<TblMasterSitePathDestination>();
            this.TblMasterNemoDetailRouteOptimization = new HashSet<TblMasterNemoDetailRouteOptimization>();
            this.TblMasterDailyRunResource_Alarm = new HashSet<TblMasterDailyRunResource_Alarm>();
            this.TblTransactionRouteOptimizationHeader_Detail_Item = new HashSet<TblTransactionRouteOptimizationHeader_Detail_Item>();
            this.TblMasterConAndDeconsolidate_Header = new HashSet<TblMasterConAndDeconsolidate_Header>();
            this.TblVaultBalance_Discrepancy = new HashSet<TblVaultBalance_Discrepancy>();
            this.TblVaultBalance_Discrepancy1 = new HashSet<TblVaultBalance_Discrepancy>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomer_Guid { get; set; }
        public Nullable<System.Guid> SystemCustomerOfType_Guid { get; set; }
        public Nullable<System.Guid> SystemCustomerLocationType_Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> MasterCity_Guid { get; set; }
        public string StateName { get; set; }
        public Nullable<System.Guid> MasterDistrict_Guid { get; set; }
        public string CitryName { get; set; }
        public Nullable<System.Guid> MasterPlace_Guid { get; set; }
        public Nullable<System.Guid> MasterServiceHour_Guid { get; set; }
        public string BranchCodeReference { get; set; }
        public string BranchName { get; set; }
        public string BranchAbbrevaitionName { get; set; }
        public string BranchProgramName { get; set; }
        public string BranchReportName { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ContractName { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public string Restrictions { get; set; }
        public string CardReturnBranch { get; set; }
        public byte[] QR_Code { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> ServiceDuration { get; set; }
        public Nullable<bool> FlagDefaultServiceHours { get; set; }
        public bool FlagSmokeBox { get; set; }
        public string EmergencyProcedures { get; set; }
        public string AccessRequirments { get; set; }
        public string AlarmActivationCode { get; set; }
        public string AlarmDuressCode { get; set; }
        public bool FlagOutOfTown { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<System.Guid> SystemGlobalUnit_Distance_Guid { get; set; }
        public Nullable<double> CeilingHeight { get; set; }
        public Nullable<System.Guid> SystemGlobalUnit_CeilingHeight_Guid { get; set; }
        public Nullable<int> WaitingMinute { get; set; }
        public Nullable<short> ReportOrderPriority { get; set; }
        public bool FlagExchangeMoney { get; set; }
        public Nullable<bool> FlagHaveAirport { get; set; }
        public string ExternalID { get; set; }
        public Nullable<System.DateTime> StartofService { get; set; }
        public Nullable<System.DateTime> EndofService { get; set; }
        public Nullable<int> PeriodofServiceDay { get; set; }
        public Nullable<int> PeriodofServiceMonth { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<int> OnwardDestinationType { get; set; }
        public Nullable<System.Guid> OnwardDestination_Guid { get; set; }
        public string CustomerLocationExtrnalID { get; set; }
        public Nullable<System.Guid> MasterCountry_State_Guid { get; set; }
        public Nullable<bool> FlagPrintReceive { get; set; }
        public Nullable<bool> FlagSendPodEmail { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<System.Guid> SystemTimezone_Guid { get; set; }
        public Nullable<bool> FlagDefaultCommodity { get; set; }
        public string PdfPassword { get; set; }
        public string ExtBranchID { get; set; }
        public string ExtBranchName { get; set; }
        public Nullable<System.Guid> MasterNonBillable_Guid { get; set; }
        public Nullable<System.DateTime> StartServiceDate { get; set; }
        public Nullable<System.DateTime> EndServiceDate { get; set; }
        public Nullable<System.Guid> SFOCashBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOServicingBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOFLMBranch_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterFLMZone_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterECashZone_Guid { get; set; }
        public Nullable<System.Guid> SFOMasterCompuSafeZone_Guid { get; set; }
        public Nullable<System.Guid> SFOCountryTimeZone_Guid { get; set; }
        public bool FlagSFOBranch { get; set; }
        public bool FlagNonBillable { get; set; }
        public bool FlagCommentOnDPNotReq { get; set; }
        public Nullable<System.Guid> MasterLocationReportGroup_Guid { get; set; }
        public string Branch { get; set; }
        public string UpperLock { get; set; }
        public string LowerLock { get; set; }
        public string LockMode { get; set; }
        public string LockUser { get; set; }
        public Nullable<bool> FlagSendMissedStop { get; set; }
        public string EmailUnableServiceNotification { get; set; }
        public Nullable<decimal> PremiseTime { get; set; }
        public Nullable<int> RiskLevelRating { get; set; }
        public Nullable<System.Guid> MasterGeoZone_Guid { get; set; }
        public Nullable<System.Guid> SystemAirportType_Guid { get; set; }
        public string LocationAddress3 { get; set; }
        public string LocationAddress4 { get; set; }
        public bool FlagSftp_POD { get; set; }
        public bool FlagGenUnableToServiceReport { get; set; }
        public bool FlagUseSftpPubKey { get; set; }
        public string PODReference { get; set; }
        public Nullable<System.DateTime> LastNemoSync { get; set; }
        public Nullable<System.Guid> SystemReportStyle_Guid { get; set; }
        public string ReferenceId { get; set; }
        public bool FlagShowLayoutSealOnly { get; set; }
        public Nullable<System.Guid> MasterPlaceRelated_Guid { get; set; }
        public bool FlagPrintReceiptEachSeal { get; set; }
        public decimal PavementLimit { get; set; }
        public Nullable<System.Guid> PavementLimitCurrency_Guid { get; set; }
        public string ISAClientCode { get; set; }
        public bool FlagObsolete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation_Location_Mapping> TblLeedToCashQuotation_Location_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerContract_ServiceLocation> TblMasterCustomerContract_ServiceLocation { get; set; }
        public virtual SFOTblMasterMachine SFOTblMasterMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest> SFOTblTransactionServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_BrinksSite> TblMasterCustomerLocation_BrinksSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_LocationDestination> TblMasterCustomerLocation_LocationDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_LocationDestination> TblMasterCustomerLocation_LocationDestination1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_ServiceHour> TblMasterCustomerLocation_ServiceHour { get; set; }
        public virtual SFOTblMasterCountryTimeZone SFOTblMasterCountryTimeZone { get; set; }
        public virtual TblSystemTimezone TblSystemTimezone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSitePathDestination> TblMasterSitePathDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterNemoDetailRouteOptimization> TblMasterNemoDetailRouteOptimization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterDailyRunResource_Alarm> TblMasterDailyRunResource_Alarm { get; set; }
        public virtual TblMasterPlace TblMasterPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransactionRouteOptimizationHeader_Detail_Item> TblTransactionRouteOptimizationHeader_Detail_Item { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
        public virtual TblMasterSite TblMasterSite1 { get; set; }
        public virtual TblMasterSite TblMasterSite2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterConAndDeconsolidate_Header> TblMasterConAndDeconsolidate_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy1 { get; set; }
    }
}
