//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobMCSBulkDepositReportEntry
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterMCSBulkDepositReport_Guid { get; set; }
        public System.Guid SFOTblMasterCassette_Guid { get; set; }
        public string CassetteName { get; set; }
        public decimal Amount { get; set; }
        public int CassetteSequence { get; set; }
        public int NumberOfNote { get; set; }
    
        public virtual TblMasterActualJobMCSBulkDepositReport TblMasterActualJobMCSBulkDepositReport { get; set; }
        public virtual SFOTblMasterCassette SFOTblMasterCassette { get; set; }
    }
}
