//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobMCSCITDelivery
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterActualJobHeader_Guid { get; set; }
        public System.Guid MasterActualJobServiceStopLegs_Guid { get; set; }
        public System.Guid MasterCurrency_Guid { get; set; }
        public string SealNo { get; set; }
        public Nullable<System.DateTime> DeliveryDatetime { get; set; }
        public Nullable<decimal> STCValue { get; set; }
        public Nullable<int> CITDeliveryStatus { get; set; }
        public Nullable<int> CustomerOrderNo { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<System.Guid> SystemMCSCITDeliveryCommodityType_Guid { get; set; }
        public Nullable<System.Guid> MasterReasonType_Guid { get; set; }
        public string MasterReasonType_ReasonTypename { get; set; }
        public string CommentIfNotReceived { get; set; }
        public Nullable<System.Guid> SystemMCSCITDeliveryScanStatus_Guid { get; set; }
        public string CustomerOrderNumber { get; set; }
        public int TypeCITBagID { get; set; }
    
        public virtual TblMasterActualJobServiceStopLegs TblMasterActualJobServiceStopLegs { get; set; }
        public virtual TblMasterReasonType TblMasterReasonType { get; set; }
        public virtual TblSystemMCSCITDeliveryCommodityType TblSystemMCSCITDeliveryCommodityType { get; set; }
        public virtual TblSystemMCSCITDeliveryScanStatus TblSystemMCSCITDeliveryScanStatus { get; set; }
        public virtual TblMasterActualJobHeader TblMasterActualJobHeader { get; set; }
    }
}
