//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterReport
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> MasterReportIndex { get; set; }
        public string MasterReportName { get; set; }
        public bool FlagDisable { get; set; }
        public Nullable<System.Guid> SystemReportType_Guid { get; set; }
        public Nullable<bool> FlagDefaultReport { get; set; }
        public Nullable<bool> FlagGlobalAdmin { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public string PageLink { get; set; }
        public string ReportFileName { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public Nullable<int> ActionControlID { get; set; }
        public string ReportFileName_Rdlc { get; set; }
    }
}
