//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCheckList
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public string CheckListName { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.Guid> SystemMachineCapability_Guid { get; set; }
        public bool FlagRequired { get; set; }
        public bool FlagAllCapability { get; set; }
    
        public virtual SFOTblSystemMachineCapability SFOTblSystemMachineCapability { get; set; }
    }
}
