//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerContract_ServiceLocation
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomerContract_Guid { get; set; }
        public System.Guid MasterCustomerLocation_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashProduct_PricingRule_Guid { get; set; }
        public Nullable<System.Guid> LeedToCashProduct_Guid { get; set; }
        public Nullable<System.Guid> LeadToCashContractAddendumDetail_Guid { get; set; }
        public Nullable<System.Guid> PricingRule_Guid { get; set; }
        public Nullable<System.Guid> SystemLineOfBusiness_Guid { get; set; }
        public Nullable<System.Guid> SystemServiceJobType_Guid { get; set; }
        public Nullable<System.Guid> SystemSubServiceType_Guid { get; set; }
    
        public virtual TblLeedToCashProduct TblLeedToCashProduct { get; set; }
        public virtual TblMasterCustomerContract TblMasterCustomerContract { get; set; }
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblPricingRule TblPricingRule { get; set; }
    }
}
