//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCurrency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCurrency()
        {
            this.TblLeedToCashProduct_ProductAttribute_Limit_Values = new HashSet<TblLeedToCashProduct_ProductAttribute_Limit_Values>();
            this.TblMasterActualJobActualCount = new HashSet<TblMasterActualJobActualCount>();
            this.TblMasterActualJobCashAdd = new HashSet<TblMasterActualJobCashAdd>();
            this.TblMasterActualJobCashReturn = new HashSet<TblMasterActualJobCashReturn>();
            this.TblMasterActualJobMachineReport = new HashSet<TblMasterActualJobMachineReport>();
            this.TblMasterActualJobSumActualCount = new HashSet<TblMasterActualJobSumActualCount>();
            this.TblMasterActualJobSumCashReturn = new HashSet<TblMasterActualJobSumCashReturn>();
            this.TblMasterActualJobSumMachineReport = new HashSet<TblMasterActualJobSumMachineReport>();
            this.SFOTblMasterMachine_Cassette = new HashSet<SFOTblMasterMachine_Cassette>();
            this.SFOTblMasterMachine_ECash = new HashSet<SFOTblMasterMachine_ECash>();
            this.TblPricingRule = new HashSet<TblPricingRule>();
            this.TblMasterActualJobMCSBulkDepositReport = new HashSet<TblMasterActualJobMCSBulkDepositReport>();
            this.TblMasterActualJobMCSBulkJammed = new HashSet<TblMasterActualJobMCSBulkJammed>();
            this.TblMasterActualJobMCSBulkJammedEntry = new HashSet<TblMasterActualJobMCSBulkJammedEntry>();
            this.TblMasterActualJobMCSBulkRetract = new HashSet<TblMasterActualJobMCSBulkRetract>();
            this.TblMasterActualJobMCSBulkRetractEntry = new HashSet<TblMasterActualJobMCSBulkRetractEntry>();
            this.TblMasterActualJobMCSBulkSuspectFakeDetail = new HashSet<TblMasterActualJobMCSBulkSuspectFakeDetail>();
            this.TblMasterActualJobMCSBulkSuspectFakeEntry = new HashSet<TblMasterActualJobMCSBulkSuspectFakeEntry>();
            this.TblMasterActualJobMCSCoinBulkNoteCollect = new HashSet<TblMasterActualJobMCSCoinBulkNoteCollect>();
            this.TblMasterActualJobMCSCoinBulkNoteCollectEntry = new HashSet<TblMasterActualJobMCSCoinBulkNoteCollectEntry>();
            this.TblMasterActualJobMCSCoinCashAdd = new HashSet<TblMasterActualJobMCSCoinCashAdd>();
            this.TblMasterActualJobMCSCoinCashAddEntry = new HashSet<TblMasterActualJobMCSCoinCashAddEntry>();
            this.TblMasterActualJobMCSCoinCashReturn = new HashSet<TblMasterActualJobMCSCoinCashReturn>();
            this.TblMasterActualJobMCSCoinCashReturnEntry = new HashSet<TblMasterActualJobMCSCoinCashReturnEntry>();
            this.TblMasterActualJobMCSCoinMachineBalance = new HashSet<TblMasterActualJobMCSCoinMachineBalance>();
            this.TblMasterActualJobMCSCoinMachineBalanceEntry = new HashSet<TblMasterActualJobMCSCoinMachineBalanceEntry>();
            this.TblMasterActualJobMCSCoinSuspectFake = new HashSet<TblMasterActualJobMCSCoinSuspectFake>();
            this.TblMasterActualJobMCSCoinSuspectFakeDetail = new HashSet<TblMasterActualJobMCSCoinSuspectFakeDetail>();
            this.TblMasterActualJobMCSCoinSuspectFakeEntry = new HashSet<TblMasterActualJobMCSCoinSuspectFakeEntry>();
            this.TblMasterActualJobMCSRecyclingActualCountEntry = new HashSet<TblMasterActualJobMCSRecyclingActualCountEntry>();
            this.TblMasterActualJobMCSRecyclingCashRecycling = new HashSet<TblMasterActualJobMCSRecyclingCashRecycling>();
            this.TblMasterActualJobMCSRecyclingCashRecyclingEntry = new HashSet<TblMasterActualJobMCSRecyclingCashRecyclingEntry>();
            this.TblMasterActualJobMCSRecyclingMachineReport = new HashSet<TblMasterActualJobMCSRecyclingMachineReport>();
            this.TblMasterActualJobMCSRecyclingMachineReportEntry = new HashSet<TblMasterActualJobMCSRecyclingMachineReportEntry>();
            this.TblMasterActualJobMCSBulkSuspectFake = new HashSet<TblMasterActualJobMCSBulkSuspectFake>();
            this.SFOTblMasterMachineModelType_DefaultCassette = new HashSet<SFOTblMasterMachineModelType_DefaultCassette>();
            this.TblMasterActualJobMCSRecyclingActualCount = new HashSet<TblMasterActualJobMCSRecyclingActualCount>();
            this.TblMasterActualJobSumCashAdd = new HashSet<TblMasterActualJobSumCashAdd>();
            this.TblMasterRunResource = new HashSet<TblMasterRunResource>();
            this.TblMasterCustomer = new HashSet<TblMasterCustomer>();
            this.TblMasterCustomerLocation = new HashSet<TblMasterCustomerLocation>();
            this.TblMasterCurrency_ExchangeRate = new HashSet<TblMasterCurrency_ExchangeRate>();
            this.TblMasterCurrency_ExchangeRate1 = new HashSet<TblMasterCurrency_ExchangeRate>();
        }
    
        public System.Guid Guid { get; set; }
        public string MasterCurrencyAbbreviation { get; set; }
        public string MasterCurrencyReportDisplay { get; set; }
        public string MasterCurrencyDescription { get; set; }
        public decimal MasterCurrencyDiscrepancyAcceptable { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string Symbol { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct_ProductAttribute_Limit_Values> TblLeedToCashProduct_ProductAttribute_Limit_Values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobActualCount> TblMasterActualJobActualCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobCashAdd> TblMasterActualJobCashAdd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobCashReturn> TblMasterActualJobCashReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMachineReport> TblMasterActualJobMachineReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumActualCount> TblMasterActualJobSumActualCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumCashReturn> TblMasterActualJobSumCashReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumMachineReport> TblMasterActualJobSumMachineReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_Cassette> SFOTblMasterMachine_Cassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_ECash> SFOTblMasterMachine_ECash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPricingRule> TblPricingRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkDepositReport> TblMasterActualJobMCSBulkDepositReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkJammed> TblMasterActualJobMCSBulkJammed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkJammedEntry> TblMasterActualJobMCSBulkJammedEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkRetract> TblMasterActualJobMCSBulkRetract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkRetractEntry> TblMasterActualJobMCSBulkRetractEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkSuspectFakeDetail> TblMasterActualJobMCSBulkSuspectFakeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkSuspectFakeEntry> TblMasterActualJobMCSBulkSuspectFakeEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinBulkNoteCollect> TblMasterActualJobMCSCoinBulkNoteCollect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinBulkNoteCollectEntry> TblMasterActualJobMCSCoinBulkNoteCollectEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashAdd> TblMasterActualJobMCSCoinCashAdd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashAddEntry> TblMasterActualJobMCSCoinCashAddEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashReturn> TblMasterActualJobMCSCoinCashReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashReturnEntry> TblMasterActualJobMCSCoinCashReturnEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinMachineBalance> TblMasterActualJobMCSCoinMachineBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinMachineBalanceEntry> TblMasterActualJobMCSCoinMachineBalanceEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFake> TblMasterActualJobMCSCoinSuspectFake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFakeDetail> TblMasterActualJobMCSCoinSuspectFakeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFakeEntry> TblMasterActualJobMCSCoinSuspectFakeEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingActualCountEntry> TblMasterActualJobMCSRecyclingActualCountEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingCashRecycling> TblMasterActualJobMCSRecyclingCashRecycling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingCashRecyclingEntry> TblMasterActualJobMCSRecyclingCashRecyclingEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingMachineReport> TblMasterActualJobMCSRecyclingMachineReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingMachineReportEntry> TblMasterActualJobMCSRecyclingMachineReportEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkSuspectFake> TblMasterActualJobMCSBulkSuspectFake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType_DefaultCassette> SFOTblMasterMachineModelType_DefaultCassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingActualCount> TblMasterActualJobMCSRecyclingActualCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumCashAdd> TblMasterActualJobSumCashAdd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterRunResource> TblMasterRunResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomer> TblMasterCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation> TblMasterCustomerLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCurrency_ExchangeRate> TblMasterCurrency_ExchangeRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCurrency_ExchangeRate> TblMasterCurrency_ExchangeRate1 { get; set; }
    }
}
