//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterDenomination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterDenomination()
        {
            this.TblMasterActualJobActualCount = new HashSet<TblMasterActualJobActualCount>();
            this.TblMasterActualJobCashAdd = new HashSet<TblMasterActualJobCashAdd>();
            this.TblMasterActualJobCashReturn = new HashSet<TblMasterActualJobCashReturn>();
            this.TblMasterActualJobMachineReport = new HashSet<TblMasterActualJobMachineReport>();
            this.SFOTblMasterMachine_Cassette = new HashSet<SFOTblMasterMachine_Cassette>();
            this.SFOTblMasterMachine_ECash = new HashSet<SFOTblMasterMachine_ECash>();
            this.TblMasterActualJobMCSBulkJammedEntry = new HashSet<TblMasterActualJobMCSBulkJammedEntry>();
            this.TblMasterActualJobMCSBulkRetractEntry = new HashSet<TblMasterActualJobMCSBulkRetractEntry>();
            this.TblMasterActualJobMCSBulkSuspectFakeDetail = new HashSet<TblMasterActualJobMCSBulkSuspectFakeDetail>();
            this.TblMasterActualJobMCSBulkSuspectFakeEntry = new HashSet<TblMasterActualJobMCSBulkSuspectFakeEntry>();
            this.TblMasterActualJobMCSCoinBulkNoteCollectEntry = new HashSet<TblMasterActualJobMCSCoinBulkNoteCollectEntry>();
            this.TblMasterActualJobMCSCoinCashAddEntry = new HashSet<TblMasterActualJobMCSCoinCashAddEntry>();
            this.TblMasterActualJobMCSCoinCashReturnEntry = new HashSet<TblMasterActualJobMCSCoinCashReturnEntry>();
            this.TblMasterActualJobMCSCoinMachineBalanceEntry = new HashSet<TblMasterActualJobMCSCoinMachineBalanceEntry>();
            this.TblMasterActualJobMCSCoinSuspectFakeDetail = new HashSet<TblMasterActualJobMCSCoinSuspectFakeDetail>();
            this.TblMasterActualJobMCSCoinSuspectFakeEntry = new HashSet<TblMasterActualJobMCSCoinSuspectFakeEntry>();
            this.TblMasterActualJobMCSRecyclingActualCountEntry = new HashSet<TblMasterActualJobMCSRecyclingActualCountEntry>();
            this.TblMasterActualJobMCSRecyclingCashRecyclingEntry = new HashSet<TblMasterActualJobMCSRecyclingCashRecyclingEntry>();
            this.TblMasterActualJobMCSRecyclingMachineReportEntry = new HashSet<TblMasterActualJobMCSRecyclingMachineReportEntry>();
            this.TblMasterActualJobMCSCoinSuspectFakeDetail1 = new HashSet<TblMasterActualJobMCSCoinSuspectFakeDetail>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCurrency_Guid { get; set; }
        public Nullable<System.Guid> SystemDenominationType_Guid { get; set; }
        public string DenominationText { get; set; }
        public Nullable<double> DenominationValue { get; set; }
        public Nullable<int> SequenceOrder { get; set; }
        public Nullable<System.Guid> SystemDenominationDefaultUnit { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<int> Amount { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobActualCount> TblMasterActualJobActualCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobCashAdd> TblMasterActualJobCashAdd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobCashReturn> TblMasterActualJobCashReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMachineReport> TblMasterActualJobMachineReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_Cassette> SFOTblMasterMachine_Cassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine_ECash> SFOTblMasterMachine_ECash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkJammedEntry> TblMasterActualJobMCSBulkJammedEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkRetractEntry> TblMasterActualJobMCSBulkRetractEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkSuspectFakeDetail> TblMasterActualJobMCSBulkSuspectFakeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkSuspectFakeEntry> TblMasterActualJobMCSBulkSuspectFakeEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinBulkNoteCollectEntry> TblMasterActualJobMCSCoinBulkNoteCollectEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashAddEntry> TblMasterActualJobMCSCoinCashAddEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashReturnEntry> TblMasterActualJobMCSCoinCashReturnEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinMachineBalanceEntry> TblMasterActualJobMCSCoinMachineBalanceEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFakeDetail> TblMasterActualJobMCSCoinSuspectFakeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFakeEntry> TblMasterActualJobMCSCoinSuspectFakeEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingActualCountEntry> TblMasterActualJobMCSRecyclingActualCountEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingCashRecyclingEntry> TblMasterActualJobMCSRecyclingCashRecyclingEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingMachineReportEntry> TblMasterActualJobMCSRecyclingMachineReportEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFakeDetail> TblMasterActualJobMCSCoinSuspectFakeDetail1 { get; set; }
    }
}
