//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterHistoryLogPodByService
    {
        public System.Guid Guid { get; set; }
        public int PodTypeID { get; set; }
        public string PodTypeName { get; set; }
        public string CustomerName { get; set; }
        public string LocationName { get; set; }
        public string RouteGroupDetailName { get; set; }
        public bool PerStop { get; set; }
        public bool SuccessStatus { get; set; }
        public string Destination { get; set; }
        public string PathFile { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public string JobNo { get; set; }
        public string ActionType { get; set; }
        public string ReportFileName { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
    }
}
