//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRoute_RouteGroupDetailMonitoring_Mapping
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterRoute_Guid { get; set; }
        public Nullable<System.Guid> MasterRouteGroup_Detail_Guid { get; set; }
        public int AM_mins { get; set; }
        public string AM_Note { get; set; }
        public int PM_mins { get; set; }
        public string PM_Note { get; set; }
        public int RAMP_mins { get; set; }
        public string RAMP_Note { get; set; }
        public int Duration { get; set; }
        public string Duration_Note { get; set; }
        public bool FlagMonitoring { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
    }
}
