//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerLocation_InternalDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCustomerLocation_InternalDepartment()
        {
            this.TblVaultBalanceHeader = new HashSet<TblVaultBalanceHeader>();
            this.TblVaultBalance_Discrepancy = new HashSet<TblVaultBalance_Discrepancy>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomerLocation_Guid { get; set; }
        public System.Guid InternalDepartmentType { get; set; }
        public string InterDepartmentName { get; set; }
        public string InternalDepartmentReferenceCode { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagCanCheckIn { get; set; }
        public Nullable<bool> FlagCanCheckOut { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<System.Guid> PrevaultAssocGuid { get; set; }
        public bool FlagIntegratedwithISA { get; set; }
        public string ISAInternalRouteCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalanceHeader> TblVaultBalanceHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy { get; set; }
    }
}
