//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerLocation_ServiceHour
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomerLocation_Guid { get; set; }
        public System.Guid SystemServiceJobType_Guid { get; set; }
        public System.Guid SystemDayOfWeek_Guid { get; set; }
        public Nullable<System.DateTime> ServiceHourStart { get; set; }
        public Nullable<System.DateTime> ServiceHourStop { get; set; }
        public bool FlagSpotTime { get; set; }
        public Nullable<System.Guid> MasterLineOfBusiness_Guid { get; set; }
        public bool FlagDefaultFromCustomer { get; set; }
        public Nullable<System.Guid> MasterRouteJobHeader_Guid { get; set; }
        public Nullable<System.Guid> MasterRouteGroupDetail_Guid { get; set; }
        public Nullable<System.DateTime> LastNemoSync { get; set; }
        public string ReferenceId { get; set; }
    
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblSystemDayOfWeek TblSystemDayOfWeek { get; set; }
        public virtual TblSystemLineOfBusiness TblSystemLineOfBusiness { get; set; }
        public virtual TblSystemServiceJobType TblSystemServiceJobType { get; set; }
    }
}
