//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCountry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCountry()
        {
            this.TblLeedToCashMasterCategoryClause = new HashSet<TblLeedToCashMasterCategoryClause>();
            this.TblLeedToCashMasterClause = new HashSet<TblLeedToCashMasterClause>();
            this.TblLeedToCashProduct = new HashSet<TblLeedToCashProduct>();
            this.TblLeedToCashQuotation = new HashSet<TblLeedToCashQuotation>();
            this.TblMasterCommodityCountry = new HashSet<TblMasterCommodityCountry>();
            this.TblMasterUserAccessGroupCountryEmail = new HashSet<TblMasterUserAccessGroupCountryEmail>();
            this.SFOTblMasterCountryTimeZone = new HashSet<SFOTblMasterCountryTimeZone>();
            this.SFOTblMasterEscalationHeader = new HashSet<SFOTblMasterEscalationHeader>();
            this.SFOTblMasterMachineModelType = new HashSet<SFOTblMasterMachineModelType>();
            this.SFOTblMasterMachineServiceType = new HashSet<SFOTblMasterMachineServiceType>();
            this.SFOTblMasterProblem = new HashSet<SFOTblMasterProblem>();
            this.SFOTblMasterSolution = new HashSet<SFOTblMasterSolution>();
            this.SFOTblSystemAllowServiceRequestStatusDuplicate = new HashSet<SFOTblSystemAllowServiceRequestStatusDuplicate>();
            this.SFOTblSystemDataConfiguration_Country = new HashSet<SFOTblSystemDataConfiguration_Country>();
            this.SFOTblSystemEscalationRuleHeader = new HashSet<SFOTblSystemEscalationRuleHeader>();
            this.SFOTblSystemOTCLockMode = new HashSet<SFOTblSystemOTCLockMode>();
            this.TblMasterSalesLevel = new HashSet<TblMasterSalesLevel>();
            this.TblMasterSalesTeam = new HashSet<TblMasterSalesTeam>();
            this.TblMasterSiteNetwork = new HashSet<TblMasterSiteNetwork>();
            this.TblMasterUserEmailTemplate = new HashSet<TblMasterUserEmailTemplate>();
            this.TblSystemNotificationConfigPeriods = new HashSet<TblSystemNotificationConfigPeriods>();
            this.SFOTblMasterCassette = new HashSet<SFOTblMasterCassette>();
            this.SFOTblMasterMonitoringNetwork = new HashSet<SFOTblMasterMonitoringNetwork>();
            this.TblMasterCurrency_ExchangeRate = new HashSet<TblMasterCurrency_ExchangeRate>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid SystemGlobalRegion_Guid { get; set; }
        public string MasterCountryName { get; set; }
        public string MasterCountryAbbreviation { get; set; }
        public string MasterCountryPathImage { get; set; }
        public Nullable<bool> FlagInputCityManual { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagSortCityByIndex { get; set; }
        public Nullable<bool> FlagHaveState { get; set; }
        public string MobilePrefixCode { get; set; }
        public Nullable<System.Guid> SystemLanguage_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashMasterCategoryClause> TblLeedToCashMasterCategoryClause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashMasterClause> TblLeedToCashMasterClause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct> TblLeedToCashProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation> TblLeedToCashQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCommodityCountry> TblMasterCommodityCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterUserAccessGroupCountryEmail> TblMasterUserAccessGroupCountryEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterCountryTimeZone> SFOTblMasterCountryTimeZone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterEscalationHeader> SFOTblMasterEscalationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType> SFOTblMasterMachineModelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineServiceType> SFOTblMasterMachineServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterProblem> SFOTblMasterProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterSolution> SFOTblMasterSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemAllowServiceRequestStatusDuplicate> SFOTblSystemAllowServiceRequestStatusDuplicate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemDataConfiguration_Country> SFOTblSystemDataConfiguration_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemEscalationRuleHeader> SFOTblSystemEscalationRuleHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemOTCLockMode> SFOTblSystemOTCLockMode { get; set; }
        public virtual TblSystemLanguage TblSystemLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSalesLevel> TblMasterSalesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSalesTeam> TblMasterSalesTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSiteNetwork> TblMasterSiteNetwork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterUserEmailTemplate> TblMasterUserEmailTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSystemNotificationConfigPeriods> TblSystemNotificationConfigPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterCassette> SFOTblMasterCassette { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMonitoringNetwork> SFOTblMasterMonitoringNetwork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCurrency_ExchangeRate> TblMasterCurrency_ExchangeRate { get; set; }
    }
}
