//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterSitePathHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterSitePathHeader()
        {
            this.TblMasterCustomerLocation_LocationDestination = new HashSet<TblMasterCustomerLocation_LocationDestination>();
            this.TblMasterRouteJobHeader = new HashSet<TblMasterRouteJobHeader>();
            this.TblMasterSitePathAuditLog = new HashSet<TblMasterSitePathAuditLog>();
            this.TblMasterSitePathDestination = new HashSet<TblMasterSitePathDestination>();
            this.TblMasterSitePathDetail = new HashSet<TblMasterSitePathDetail>();
            this.TblMasterActualJobHeader = new HashSet<TblMasterActualJobHeader>();
            this.TblBankCleanOutJobDelivery_Temp = new HashSet<TblBankCleanOutJobDelivery_Temp>();
            this.TblMasterConAndDeconsolidate_Header = new HashSet<TblMasterConAndDeconsolidate_Header>();
            this.TblMasterConAndDeconsolidate_Header1 = new HashSet<TblMasterConAndDeconsolidate_Header>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterSiteNetwork_Guid { get; set; }
        public string SitePathName { get; set; }
        public bool FlagDisble { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreted { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_LocationDestination> TblMasterCustomerLocation_LocationDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterRouteJobHeader> TblMasterRouteJobHeader { get; set; }
        public virtual TblMasterSiteNetwork TblMasterSiteNetwork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSitePathAuditLog> TblMasterSitePathAuditLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSitePathDestination> TblMasterSitePathDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSitePathDetail> TblMasterSitePathDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobHeader> TblMasterActualJobHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBankCleanOutJobDelivery_Temp> TblBankCleanOutJobDelivery_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterConAndDeconsolidate_Header> TblMasterConAndDeconsolidate_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterConAndDeconsolidate_Header> TblMasterConAndDeconsolidate_Header1 { get; set; }
    }
}
