//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterDistrict()
        {
            this.TblLeedToCashProduct_ProductAttribute_GeoLocation_City = new HashSet<TblLeedToCashProduct_ProductAttribute_GeoLocation_City>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCity_Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_State_Guid { get; set; }
        public string MasterDistrictName { get; set; }
        public string MasterDistrictAbbreviation { get; set; }
        public string Postcode { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> SystemLeedToCashCityType_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct_ProductAttribute_GeoLocation_City> TblLeedToCashProduct_ProductAttribute_GeoLocation_City { get; set; }
    }
}
