//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterEmployee()
        {
            this.TblMasterDailyRunResource_Alarm = new HashSet<TblMasterDailyRunResource_Alarm>();
            this.TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer = new HashSet<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer>();
            this.TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer1 = new HashSet<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer>();
        }
    
        public System.Guid Guid { get; set; }
        public string StaffID { get; set; }
        public string IdentificationNumber { get; set; }
        public Nullable<System.Guid> SystemTitleName_Guid { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> MasterInternalDepartment_Guid { get; set; }
        public Nullable<System.Guid> MasterPosition_Guid { get; set; }
        public Nullable<System.Guid> MasterEmployeeStatus_Guid { get; set; }
        public string TouchKey_ID { get; set; }
        public string PIN { get; set; }
        public string MobileLoginPIN { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<System.DateTime> StartTimeWorking { get; set; }
        public Nullable<System.DateTime> EndTimeWorking { get; set; }
        public Nullable<System.DateTime> ExpiryDateEmployeeCard { get; set; }
        public string MedicalRestricion { get; set; }
        public string PathImage { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> FlagWithdrawSealForOtherPurposes { get; set; }
        public Nullable<bool> FlagWithdrawSealWithoutRunAssignment { get; set; }
        public Nullable<bool> FlagAuthorizedToCollectParcels { get; set; }
        public Nullable<bool> FlagAuthorizedToCollectDocument { get; set; }
        public Nullable<bool> FlagATMCertified { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string MobileLoginPIN_Text { get; set; }
        public Nullable<System.Guid> MasterEmployeeDepartment_Guid { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<System.Guid> SystemGlobalUnitMeasure_Guid { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<System.Guid> SystemGlobalUnitWeight_Guid { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string SocialIndenficationNumber { get; set; }
        public string PayrollAccountNumber { get; set; }
        public Nullable<System.Guid> SystemBloodGroup_Guid { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagApproveSiglist { get; set; }
        public string MobileSystemID { get; set; }
        public string MoblieLoginPWD { get; set; }
        public string MoblieLoginPWD_Text { get; set; }
        public string CrewBreakStatus { get; set; }
        public string ImagePathMVC { get; set; }
        public bool FlagVaultCashierUser { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> CostPer { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ExtraCost { get; set; }
        public string DuressCode { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<System.Guid> SaltKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterDailyRunResource_Alarm> TblMasterDailyRunResource_Alarm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer> TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer> TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer1 { get; set; }
    }
}
