//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRunResource_GasolineExpense
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterSite_Guid { get; set; }
        public System.Guid MasterRunResource_Guid { get; set; }
        public System.DateTime TopUpDate { get; set; }
        public decimal TopUpAmount { get; set; }
        public System.Guid CurrencyAmount_Guid { get; set; }
        public double TopUpQty { get; set; }
        public decimal Unit_Price { get; set; }
        public System.Guid CurrencyUnit_Guid { get; set; }
        public System.Guid MasterGasloine_Guid { get; set; }
        public string DocumentRef { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string OdoMeter { get; set; }
        public Nullable<System.Guid> TopupQtyUnit_Guid { get; set; }
    }
}
