//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRouteGroup
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public string MasterRouteGroupName { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModifed { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModifed { get; set; }
        public string EmailTo { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public string ReferenceId { get; set; }
    }
}
