//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterRoute()
        {
            this.TblMasterDailyRunResource = new HashSet<TblMasterDailyRunResource>();
            this.TblMasterDailyRunResource1 = new HashSet<TblMasterDailyRunResource>();
            this.TblTransactionRouteOptimizationHeader = new HashSet<TblTransactionRouteOptimizationHeader>();
            this.TblMasterRoute_OptimizationStatus = new HashSet<TblMasterRoute_OptimizationStatus>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterDayOfweek_Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public string MasterRouteName { get; set; }
        public string MasterRouteDescription { get; set; }
        public Nullable<bool> FlagHoliday { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public Nullable<System.Guid> SystemMasterRouteType_Guid { get; set; }
        public int AM_mins { get; set; }
        public string AM_Note { get; set; }
        public int PM_mins { get; set; }
        public string PM_Note { get; set; }
        public int RAMP_mins { get; set; }
        public string RAMP_Note { get; set; }
        public System.Guid SystemMaterRouteTypeOfWeek_Guid { get; set; }
        public int Duration { get; set; }
        public string Duration_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterDailyRunResource> TblMasterDailyRunResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterDailyRunResource> TblMasterDailyRunResource1 { get; set; }
        public virtual TblSystemMaterRouteTypeOfWeek TblSystemMaterRouteTypeOfWeek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransactionRouteOptimizationHeader> TblTransactionRouteOptimizationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterRoute_OptimizationStatus> TblMasterRoute_OptimizationStatus { get; set; }
    }
}
