//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobMCSCoinCashReturnEntry
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterActualJobMCSCoinCashReturn_Guid { get; set; }
        public System.Guid MasterCurrency_Guid { get; set; }
        public string CurrencyAbbr { get; set; }
        public System.Guid MasterDenomination_Guid { get; set; }
        public decimal DenominationValue { get; set; }
        public decimal HopperValue { get; set; }
        public int Return { get; set; }
        public int Stay { get; set; }
        public int Diff { get; set; }
        public System.Guid SystemCassetteType_Guid { get; set; }
        public int CassetteTypeID { get; set; }
        public int CassetteSequence { get; set; }
    
        public virtual TblMasterActualJobMCSCoinCashReturn TblMasterActualJobMCSCoinCashReturn { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        public virtual TblMasterDenomination TblMasterDenomination { get; set; }
        public virtual TblSystemCassetteType TblSystemCassetteType { get; set; }
    }
}
