//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCustomerContract()
        {
            this.TblLeedToCashContract_PricingRules = new HashSet<TblLeedToCashContract_PricingRules>();
            this.TblMasterCustomerContract_ServiceLocation = new HashSet<TblMasterCustomerContract_ServiceLocation>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomer_Guid { get; set; }
        public string ContractNo { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ContractStartedDate { get; set; }
        public Nullable<System.DateTime> ContractExpiredDate { get; set; }
        public string Telephone { get; set; }
        public string FaxNo { get; set; }
        public bool FlagCheckBeforeCreateJob { get; set; }
        public bool FlagValid { get; set; }
        public string ContractReference { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagAutoRenew { get; set; }
        public Nullable<System.Guid> RefContract_Guid { get; set; }
        public Nullable<int> RevisionNo { get; set; }
        public Nullable<System.Guid> LeedToCashQuotation_Guid { get; set; }
        public Nullable<System.Guid> BrinksCompany_Guid { get; set; }
        public Nullable<System.Guid> SalesPerson_Guid { get; set; }
        public Nullable<System.Guid> SystemLeedToCashContractStatus { get; set; }
        public string OpportunityID { get; set; }
        public Nullable<System.DateTime> RateExpiredDate { get; set; }
        public bool FlagSigned { get; set; }
        public Nullable<System.Guid> RefCurrentContract_Guid { get; set; }
        public string SignedDocumentName { get; set; }
        public string SignedID { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> FlagBrinksPrinting { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashContract_PricingRules> TblLeedToCashContract_PricingRules { get; set; }
        public virtual TblLeedToCashQuotation TblLeedToCashQuotation { get; set; }
        public virtual TblMasterCustomer TblMasterCustomer { get; set; }
        public virtual TblMasterCustomer TblMasterCustomer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerContract_ServiceLocation> TblMasterCustomerContract_ServiceLocation { get; set; }
        public virtual TblMasterUser TblMasterUser { get; set; }
        public virtual TblSystemLeedToCashContractStatus TblSystemLeedToCashContractStatus { get; set; }
    }
}
