//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterMenuDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterMenuDetail()
        {
            this.TblMasterMenuDetailCommand = new HashSet<TblMasterMenuDetailCommand>();
        }
    
        public System.Guid Guid { get; set; }
        public int MasterMenuDetailIndex { get; set; }
        public string MasterMenuDetailName { get; set; }
        public string MasterMenuDetailParentMenu { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public string MasterMenuDetailLinkToPage { get; set; }
        public string MasterMenuDetailImage { get; set; }
        public string WCFMethodService { get; set; }
        public string PageName { get; set; }
        public bool FlagDisable { get; set; }
        public Nullable<bool> FlagCustomer { get; set; }
        public Nullable<bool> FlagDefault { get; set; }
        public bool FlagGlobalAdminMenu { get; set; }
        public Nullable<bool> FlagLocalAdminMenu { get; set; }
        public Nullable<bool> FlagBrinksUserMenu { get; set; }
        public bool FlagNotProperlyMobile { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string CssClass { get; set; }
        public Nullable<int> MenuIndexOrder { get; set; }
        public Nullable<int> ActionControlID { get; set; }
        public Nullable<bool> FlagAvaliableOnMVC { get; set; }
        public int ApplicationID { get; set; }
        public string AvailableOnVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterMenuDetailCommand> TblMasterMenuDetailCommand { get; set; }
    }
}
