//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerLocation_LocationDestination
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomerLocation_Guid { get; set; }
        public System.Guid MasterCustomerLocationDes_Guid { get; set; }
        public Nullable<bool> FlagDefault { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartment_Guid { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
        public Nullable<System.Guid> MasterSitePathHeader_Guid { get; set; }
    
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation1 { get; set; }
        public virtual TblMasterSitePathHeader TblMasterSitePathHeader { get; set; }
    }
}
