//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobMCSCoinBulkNoteCollectEntry
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterActualJobMCSCoinBulkNoteCollect_Guid { get; set; }
        public System.Guid MasterCurrency_Guid { get; set; }
        public string CurrencyAbbr { get; set; }
        public System.Guid MasterDenomination_Guid { get; set; }
        public decimal DenominationValue { get; set; }
        public int All_In { get; set; }
        public decimal Amount { get; set; }
    
        public virtual TblMasterActualJobMCSCoinBulkNoteCollect TblMasterActualJobMCSCoinBulkNoteCollect { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        public virtual TblMasterDenomination TblMasterDenomination { get; set; }
    }
}
