//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCustomerLocation_BrinksSite
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterCustomerLocation_Guid { get; set; }
        public System.Guid MasterSite_Guid { get; set; }
        public bool FlagDefaultBrinksSite { get; set; }
    
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
