//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRunResource_Maintenance
    {
        public System.Guid Guid { get; set; }
        public int MaintenanceID { get; set; }
        public System.Guid MasterSite_Guid { get; set; }
        public System.Guid MasterRunResource_Guid { get; set; }
        public Nullable<System.Guid> MasterMaintenanceCategory_Guid { get; set; }
        public System.Guid MasterVendor_Guid { get; set; }
        public int MaintenanceStatusID { get; set; }
        public string Open_OdoMeter { get; set; }
        public System.DateTime Open_DateServiceFrom { get; set; }
        public System.DateTime Open_TimeServiceFrom { get; set; }
        public System.DateTime Open_DateServiceTo { get; set; }
        public System.DateTime Open_TimeServiceTo { get; set; }
        public Nullable<decimal> CostEstimate { get; set; }
        public Nullable<System.Guid> CurrencyEstimate_Guid { get; set; }
        public Nullable<decimal> CostActual { get; set; }
        public Nullable<System.Guid> CurrencyActual_Guid { get; set; }
        public string DocumentRef_No { get; set; }
        public string Remarks { get; set; }
        public string Close_OdoMeter { get; set; }
        public Nullable<System.DateTime> Close_DateService { get; set; }
        public Nullable<System.DateTime> Close_TimeService { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<int> Discount_Type { get; set; }
    }
}
