//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterHistory_ReportPushToSmart
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<int> TotalJobsExport { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public string UserNameExport { get; set; }
        public Nullable<System.DateTime> DateTimeExportReport { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public bool FlagSaveTemp { get; set; }
        public bool FlagAutoGen { get; set; }
        public bool FlagAutoGenResult { get; set; }
        public string AutoGenFileName { get; set; }
        public string AutoGenErrorMessage { get; set; }
        public string Email { get; set; }
        public bool FlagEmailSending { get; set; }
        public bool FlagEmailSendingResult { get; set; }
        public Nullable<System.DateTime> EmailSendingResultDateTime { get; set; }
        public string EmailSendingErrorMessage { get; set; }
        public string DropFilePath { get; set; }
        public bool FlagFileDroping { get; set; }
        public bool FlagFileDropingResult { get; set; }
        public Nullable<System.DateTime> FileDropingResultDateTime { get; set; }
        public string FileDropingErrorMessage { get; set; }
    }
}
