//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobHeader_OTC
    {
        public System.Guid Guid { get; set; }
        public string Country { get; set; }
        public System.Guid MasterActualJobHeader_Guid { get; set; }
        public string Branch { get; set; }
        public int LockIndex { get; set; }
        public string Lock { get; set; }
        public string LockMode { get; set; }
        public string LockType { get; set; }
        public string OTC_Code { get; set; }
        public string OTC_Code_Encrypt { get; set; }
        public string TouchKey { get; set; }
        public string PIN { get; set; }
        public Nullable<int> OTC_Time_Block { get; set; }
        public Nullable<System.DateTime> OTC_Effective_DateTime { get; set; }
        public Nullable<System.DateTime> OTC_Expire_DateTime { get; set; }
        public string ClosedSeal { get; set; }
        public string LockUser { get; set; }
        public string LockUser2 { get; set; }
        public string PIN2 { get; set; }
        public string OpenLockCode { get; set; }
        public Nullable<bool> FlagCloseSealSuccess { get; set; }
        public string CombinationCode { get; set; }
        public Nullable<System.DateTime> ClosedSealDatetime { get; set; }
        public Nullable<System.DateTime> OpenLockDatetime { get; set; }
        public Nullable<System.Guid> MasterActualJobServiceStopLegs_Guid { get; set; }
        public string MachineType { get; set; }
    
        public virtual TblMasterActualJobHeader TblMasterActualJobHeader { get; set; }
    }
}
