//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobItemDiscrapencies
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobHeader_Guid { get; set; }
        public string SealNo { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
        public Nullable<int> QtyMissing { get; set; }
        public Nullable<int> QtyOverage { get; set; }
        public Nullable<bool> FlagCloseCase { get; set; }
        public Nullable<System.Guid> MasterReasonType_Guid { get; set; }
        public string Remarks { get; set; }
        public string UsernameSupervisorVerify { get; set; }
        public Nullable<System.DateTime> DatetimeSupervisorVerify { get; set; }
        public string UsernameCloseCase { get; set; }
        public Nullable<System.DateTime> DatetimeCloseCase { get; set; }
        public string ReasonClosedCase { get; set; }
        public Nullable<System.Guid> MasterRunResourceDaily_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartment_Guid { get; set; }
        public string ClientHostNameScan { get; set; }
        public bool FlagNotification { get; set; }
        public Nullable<System.Guid> MasterConAndDeconsolidateHeader_Guid { get; set; }
    }
}
