//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterGroup()
        {
            this.TblMasterGroup_MenuCommand = new HashSet<TblMasterGroup_MenuCommand>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public string GroupName { get; set; }
        public string Email { get; set; }
        public Nullable<int> RoleType { get; set; }
        public Nullable<System.Guid> SystemRoleGroupType_Guid { get; set; }
        public string Description { get; set; }
        public bool FlagSystem { get; set; }
        public Nullable<bool> FlagGlobalAdmin { get; set; }
        public Nullable<bool> FlagLocalAdmin { get; set; }
        public Nullable<bool> FlagBrinksUser { get; set; }
        public bool FlagCustomer { get; set; }
        public string PathImage { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public bool FlagAllowAcknowledgeAlarm { get; set; }
        public bool FlagAllowDeactivateAlarm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterGroup_MenuCommand> TblMasterGroup_MenuCommand { get; set; }
    }
}
