//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRouteJobServiceStopLegs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterRouteJobServiceStopLegs()
        {
            this.TblTransactionRouteOptimizationHeader_Detail_Item = new HashSet<TblTransactionRouteOptimizationHeader_Detail_Item>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterRouteJobHeader_Guid { get; set; }
        public Nullable<int> SequenceStop { get; set; }
        public Nullable<System.Guid> MasterRouteGroupDetail_Guid { get; set; }
        public Nullable<System.Guid> CustomerLocationAction_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public Nullable<System.DateTime> SchduleTime { get; set; }
        public Nullable<int> DayOfWeek_Sequence { get; set; }
        public Nullable<bool> FlagDeliveryLegForTV { get; set; }
        public Nullable<System.Guid> MasterRouteDeliveryLeg_Guid { get; set; }
        public bool FlagDisableRoute { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<int> JobOrder { get; set; }
        public Nullable<int> SeqIndex { get; set; }
        public bool FlagMultiplesDaysJob { get; set; }
        public Nullable<int> NumberOfDaysCompletionJob { get; set; }
        public Nullable<int> DayOfWeekCompletion_Sequence { get; set; }
        public bool FlagNonBillable { get; set; }
        public bool FlagDestination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransactionRouteOptimizationHeader_Detail_Item> TblTransactionRouteOptimizationHeader_Detail_Item { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
