//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMobileATMCheckListEE
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterActualJobServiceStopLeg_Guid { get; set; }
        public Nullable<System.DateTime> CheckedDatetime { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string CheckListName { get; set; }
        public Nullable<System.Guid> MasterCheckList_Guid { get; set; }
        public bool FlagIsChecked { get; set; }
    
        public virtual TblMasterActualJobServiceStopLegs TblMasterActualJobServiceStopLegs { get; set; }
    }
}
