//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterSite()
        {
            this.TblMasterCustomerLocation = new HashSet<TblMasterCustomerLocation>();
            this.TblMasterCustomerLocation1 = new HashSet<TblMasterCustomerLocation>();
            this.TblMasterCustomerLocation2 = new HashSet<TblMasterCustomerLocation>();
            this.TblMasterCustomerLocation_BrinksSite = new HashSet<TblMasterCustomerLocation_BrinksSite>();
            this.TblMasterDailyRunResource_Alarm = new HashSet<TblMasterDailyRunResource_Alarm>();
            this.TblMasterNemoQueueRouteOptimization = new HashSet<TblMasterNemoQueueRouteOptimization>();
            this.TblMasterRouteJobServiceStopLegs = new HashSet<TblMasterRouteJobServiceStopLegs>();
            this.SFOTblMasterEscalationHeader = new HashSet<SFOTblMasterEscalationHeader>();
            this.SFOTblMasterJournal = new HashSet<SFOTblMasterJournal>();
            this.SFOTblMasterMachine = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterMachine1 = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterMachine2 = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterMachine3 = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterMachine4 = new HashSet<SFOTblMasterMachine>();
            this.SFOTblMasterMachineModelType = new HashSet<SFOTblMasterMachineModelType>();
            this.SFOTblMasterMachineServiceType = new HashSet<SFOTblMasterMachineServiceType>();
            this.SFOTblMasterProblem_Solution = new HashSet<SFOTblMasterProblem_Solution>();
            this.SFOTblMasterProblem = new HashSet<SFOTblMasterProblem>();
            this.SFOTblMasterSolution = new HashSet<SFOTblMasterSolution>();
            this.SFOTblMasterSource = new HashSet<SFOTblMasterSource>();
            this.SFOTblTransactionServiceRequest_Journal = new HashSet<SFOTblTransactionServiceRequest_Journal>();
            this.SFOTblTransactionServiceRequest_Problem = new HashSet<SFOTblTransactionServiceRequest_Problem>();
            this.SFOTblTransactionServiceRequest_Solution = new HashSet<SFOTblTransactionServiceRequest_Solution>();
            this.SFOTblTransactionServiceRequest = new HashSet<SFOTblTransactionServiceRequest>();
            this.TblMasterSiteNetworkMember = new HashSet<TblMasterSiteNetworkMember>();
            this.TblMasterSitePathDestination = new HashSet<TblMasterSitePathDestination>();
            this.TblMasterSitePathDetail = new HashSet<TblMasterSitePathDetail>();
            this.TblTransactionRouteOptimizationHeader = new HashSet<TblTransactionRouteOptimizationHeader>();
            this.TblMasterSite_SmartBillingSchedule = new HashSet<TblMasterSite_SmartBillingSchedule>();
            this.TblVaultBalanceHeader = new HashSet<TblVaultBalanceHeader>();
            this.TblMasterConAndDeconsolidate_Header = new HashSet<TblMasterConAndDeconsolidate_Header>();
            this.TblVaultBalance_Discrepancy = new HashSet<TblVaultBalance_Discrepancy>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCountry_Guid { get; set; }
        public string SiteName { get; set; }
        public string SiteCode { get; set; }
        public string Description { get; set; }
        public bool FlagDisable { get; set; }
        public bool FlagSendSignature { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public Nullable<System.Guid> MasterSiteHub_Guid { get; set; }
        public string AlphaCode { get; set; }
        public Nullable<decimal> FixedCostPerMonth { get; set; }
        public string TermConditionBody { get; set; }
        public bool FlagIntegrationSite { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string SiteAbbrevaitionName { get; set; }
        public bool FlagOTC { get; set; }
        public Nullable<System.DateTime> OTCTime { get; set; }
        public string OTCEmail { get; set; }
        public Nullable<System.DateTime> LastNemoSync { get; set; }
        public Nullable<int> MaxTimeOTC { get; set; }
        public string ReferenceId { get; set; }
        public bool FlagAutoSendDailyPlanReport { get; set; }
        public Nullable<decimal> ISACashCenterCode { get; set; }
        public Nullable<System.DateTime> OTCDailyGenerateDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation> TblMasterCustomerLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation> TblMasterCustomerLocation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation> TblMasterCustomerLocation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_BrinksSite> TblMasterCustomerLocation_BrinksSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterDailyRunResource_Alarm> TblMasterDailyRunResource_Alarm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterNemoQueueRouteOptimization> TblMasterNemoQueueRouteOptimization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterRouteJobServiceStopLegs> TblMasterRouteJobServiceStopLegs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterEscalationHeader> SFOTblMasterEscalationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterJournal> SFOTblMasterJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachine> SFOTblMasterMachine4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineModelType> SFOTblMasterMachineModelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterMachineServiceType> SFOTblMasterMachineServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterProblem_Solution> SFOTblMasterProblem_Solution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterProblem> SFOTblMasterProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterSolution> SFOTblMasterSolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterSource> SFOTblMasterSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Journal> SFOTblTransactionServiceRequest_Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Problem> SFOTblTransactionServiceRequest_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest_Solution> SFOTblTransactionServiceRequest_Solution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblTransactionServiceRequest> SFOTblTransactionServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSiteNetworkMember> TblMasterSiteNetworkMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSitePathDestination> TblMasterSitePathDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSitePathDetail> TblMasterSitePathDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransactionRouteOptimizationHeader> TblTransactionRouteOptimizationHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSite_SmartBillingSchedule> TblMasterSite_SmartBillingSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalanceHeader> TblVaultBalanceHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterConAndDeconsolidate_Header> TblMasterConAndDeconsolidate_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy { get; set; }
    }
}
