//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCapturedCard
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterActualJobHeader_Guid { get; set; }
        public string CardNo { get; set; }
        public string HolderName { get; set; }
        public string BankName { get; set; }
    
        public virtual TblMasterActualJobHeader TblMasterActualJobHeader { get; set; }
    }
}
