//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterDailyRunResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterDailyRunResource()
        {
            this.TblMasterNemoQueueRouteOptimization = new HashSet<TblMasterNemoQueueRouteOptimization>();
            this.TblMasterDailyRunResource_Alarm = new HashSet<TblMasterDailyRunResource_Alarm>();
            this.TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer = new HashSet<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer>();
            this.TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer1 = new HashSet<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer>();
            this.TblMasterHistory_DolphinAssignToAnotherRun = new HashSet<TblMasterHistory_DolphinAssignToAnotherRun>();
            this.TblTransactionRouteOptimizationHeader_Detail = new HashSet<TblTransactionRouteOptimizationHeader_Detail>();
            this.TblMasterConAndDeconsolidate_Header = new HashSet<TblMasterConAndDeconsolidate_Header>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterRunResource_Guid { get; set; }
        public Nullable<int> MasterRunResourceShift { get; set; }
        public Nullable<System.Guid> MasterRouteGroup_Detail_Guid { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<int> OdoMeterStart { get; set; }
        public Nullable<int> OdoMeterStop { get; set; }
        public Nullable<int> RunResourceDailyStatusID { get; set; }
        public Nullable<System.DateTime> RunResourceDispatchDateTime { get; set; }
        public Nullable<System.DateTime> RunResourceCloseDateTime { get; set; }
        public Nullable<bool> FlagGenOtcCodeAlready { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.DateTime> RunResourceArrivalDateTime { get; set; }
        public string GeneralRemarks { get; set; }
        public Nullable<byte> FlagSyncToExternal { get; set; }
        public Nullable<System.DateTime> LoadingStartDateTime { get; set; }
        public Nullable<System.DateTime> LoadingEndDateTime { get; set; }
        public bool FlagRouteBalanceDone { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public bool FlagAlarmLock { get; set; }
        public bool FlagBreakMasterRoute { get; set; }
        public Nullable<System.Guid> FirstMasterRoute_Guid { get; set; }
        public Nullable<System.Guid> MasterRoute_Guid { get; set; }
        public Nullable<System.DateTime> FirstGeneratedDate { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string FirstUserGenerated { get; set; }
        public string ReferenceId { get; set; }
        public bool FlagSentAutoDailyPlanReport { get; set; }
        public Nullable<System.Guid> SystemRouteOptimizationStatus_Guid { get; set; }
        public string EmployeeIDExt { get; set; }
        public string UnitIDExt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterNemoQueueRouteOptimization> TblMasterNemoQueueRouteOptimization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterDailyRunResource_Alarm> TblMasterDailyRunResource_Alarm { get; set; }
        public virtual TblMasterRoute TblMasterRoute { get; set; }
        public virtual TblMasterRoute TblMasterRoute1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer> TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer> TblMasterHistory_DailyRunResource_SignatureTruckToTruckTransfer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterHistory_DolphinAssignToAnotherRun> TblMasterHistory_DolphinAssignToAnotherRun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransactionRouteOptimizationHeader_Detail> TblTransactionRouteOptimizationHeader_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterConAndDeconsolidate_Header> TblMasterConAndDeconsolidate_Header { get; set; }
    }
}
