//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRunResource_Accident_Images
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterRunResource_Accident_Guid { get; set; }
        public string PathImage { get; set; }
        public string ImageName { get; set; }
        public string FileType { get; set; }
        public byte[] AccidentImage { get; set; }
    }
}
