//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterNemoCountryValue
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public Nullable<System.Guid> SystemGlobalUnit_Guid { get; set; }
        public Nullable<System.DateTime> LunchTime { get; set; }
        public Nullable<int> LunchDuration { get; set; }
        public bool FlagZoneUsing { get; set; }
        public bool FlagOverlapZone { get; set; }
        public Nullable<decimal> MaxOverlapDistance { get; set; }
        public Nullable<int> MaxServiceStop { get; set; }
        public Nullable<decimal> MaxLiability { get; set; }
        public Nullable<int> MaxDuration { get; set; }
        public Nullable<decimal> MaxCapacity { get; set; }
        public Nullable<decimal> MaxVolumn { get; set; }
        public Nullable<decimal> MaxDistanceBetweenStop { get; set; }
        public Nullable<int> MaxWaitTime { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<decimal> MaxRunTotalDistance { get; set; }
        public bool FlagTurnAround { get; set; }
        public Nullable<decimal> TurnAroundLeadTime { get; set; }
        public bool FlagAllowEarliestDispatchedTime { get; set; }
        public Nullable<int> MaxBayLoadingVehicle { get; set; }
        public Nullable<int> MaxBayLoadingTime { get; set; }
        public Nullable<bool> FlagOptimizeGroup { get; set; }
        public Nullable<bool> FlagOptimizeScheduleTime { get; set; }
    }
}
