//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobServiceStopLegs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterActualJobServiceStopLegs()
        {
            this.TblMasterActualJobSumActualCount = new HashSet<TblMasterActualJobSumActualCount>();
            this.TblMasterActualJobSumCashReturn = new HashSet<TblMasterActualJobSumCashReturn>();
            this.TblMasterActualJobSumMachineReport = new HashSet<TblMasterActualJobSumMachineReport>();
            this.TblMasterActualJobMCSBulkDepositReport = new HashSet<TblMasterActualJobMCSBulkDepositReport>();
            this.TblMasterActualJobMCSBulkJammed = new HashSet<TblMasterActualJobMCSBulkJammed>();
            this.TblMasterActualJobMCSBulkRetract = new HashSet<TblMasterActualJobMCSBulkRetract>();
            this.TblMasterActualJobMCSCoinBulkNoteCollect = new HashSet<TblMasterActualJobMCSCoinBulkNoteCollect>();
            this.TblMasterActualJobMCSCoinCashAdd = new HashSet<TblMasterActualJobMCSCoinCashAdd>();
            this.TblMasterActualJobMCSCoinCashReturn = new HashSet<TblMasterActualJobMCSCoinCashReturn>();
            this.TblMasterActualJobMCSCoinMachineBalance = new HashSet<TblMasterActualJobMCSCoinMachineBalance>();
            this.TblMasterActualJobMCSCoinSuspectFake = new HashSet<TblMasterActualJobMCSCoinSuspectFake>();
            this.TblMasterActualJobMCSRecyclingCashRecycling = new HashSet<TblMasterActualJobMCSRecyclingCashRecycling>();
            this.TblMasterActualJobMCSRecyclingMachineReport = new HashSet<TblMasterActualJobMCSRecyclingMachineReport>();
            this.TblMasterActualJobMCSBulkSuspectFake = new HashSet<TblMasterActualJobMCSBulkSuspectFake>();
            this.TblMobileATMCheckListEE = new HashSet<TblMobileATMCheckListEE>();
            this.TblMasterActualJobMCSCITDelivery = new HashSet<TblMasterActualJobMCSCITDelivery>();
            this.TblMasterActualJobMCSRecyclingActualCount = new HashSet<TblMasterActualJobMCSRecyclingActualCount>();
            this.TblMasterActualJobSumCashAdd = new HashSet<TblMasterActualJobSumCashAdd>();
            this.TblTransactionRouteOptimizationHeader_Detail_Item = new HashSet<TblTransactionRouteOptimizationHeader_Detail_Item>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobHeader_Guid { get; set; }
        public Nullable<int> SequenceStop { get; set; }
        public Nullable<System.Guid> CustomerLocationAction_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public Nullable<System.Guid> MasterRouteGroupDetail_Guid { get; set; }
        public Nullable<System.DateTime> ServiceStopTransectionDate { get; set; }
        public Nullable<System.DateTime> WindowsTimeServiceTimeStart { get; set; }
        public Nullable<System.DateTime> WindowsTimeServiceTimeStop { get; set; }
        public Nullable<System.DateTime> InputedDate { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> ActualTime { get; set; }
        public Nullable<System.DateTime> DepartTime { get; set; }
        public Nullable<System.Guid> MasterRunResourceDaily_Guid { get; set; }
        public Nullable<int> Odometer { get; set; }
        public Nullable<bool> FlagCancelLeg { get; set; }
        public Nullable<int> JobOrder { get; set; }
        public string LocationReferenceCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> RevisedTime { get; set; }
        public Nullable<bool> FlagEarlyFlight { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> EstimateDepartureTime { get; set; }
        public Nullable<System.DateTime> EstimateArrivalTime { get; set; }
        public Nullable<double> WeightShip { get; set; }
        public Nullable<int> Pieces { get; set; }
        public string MawbNumber { get; set; }
        public Nullable<int> NoOfHAWB { get; set; }
        public string AirportRemarks { get; set; }
        public Nullable<bool> FlagAirportDocCheck { get; set; }
        public string PrintedReceiptNumber { get; set; }
        public Nullable<System.Guid> MasterCustomerLocationAirport_Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public string RemarksLeg { get; set; }
        public Nullable<int> SystemTransportWay_ID { get; set; }
        public Nullable<System.Guid> MasterTrasportWay_Guid { get; set; }
        public string LocationNameCrewBreak { get; set; }
        public Nullable<System.DateTime> ServiceHourStart { get; set; }
        public Nullable<System.DateTime> ServiceHourEnd { get; set; }
        public bool FlagNextStop { get; set; }
        public Nullable<System.DateTime> ArrivalTime_ServiceStop { get; set; }
        public Nullable<System.DateTime> DepartTime_ServiceStop { get; set; }
        public Nullable<System.DateTime> ArrivalTime_VehicleStop { get; set; }
        public Nullable<System.DateTime> DepartTime_VehicleStop { get; set; }
        public string Arr_Lat { get; set; }
        public string Arr_Long { get; set; }
        public string Dap_Lat { get; set; }
        public string Dap_Long { get; set; }
        public Nullable<int> SeqIndex { get; set; }
        public Nullable<System.DateTime> SFOStartWaitingTechnicialDateTime { get; set; }
        public Nullable<System.DateTime> SFOStopWaitingTechnicialDateTime { get; set; }
        public Nullable<System.DateTime> SFOStartWorkingDateTime { get; set; }
        public Nullable<System.DateTime> SFOStopWorkingDateTime { get; set; }
        public Nullable<System.DateTime> ArrivePlaceDatetime { get; set; }
        public Nullable<System.DateTime> DepartPlaceDatetime { get; set; }
        public string PlaceTravelTime { get; set; }
        public bool FlagNonBillable { get; set; }
        public Nullable<int> NumberOfIncorrectLocationArrive { get; set; }
        public bool FlagDestination { get; set; }
        public Nullable<System.DateTime> UnassignedDatetime { get; set; }
        public string UnassignedBy { get; set; }
        public bool flagHaveSignature { get; set; }
        public bool FlagHaveImage { get; set; }
        public int NoOfImage { get; set; }
        public string DocIDUnableToService { get; set; }
        public string APIWindowsServiceTime { get; set; }
        public Nullable<System.Guid> SystemRouteOptimizationStatus_Guid { get; set; }
        public bool FlagShowManifest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumActualCount> TblMasterActualJobSumActualCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumCashReturn> TblMasterActualJobSumCashReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumMachineReport> TblMasterActualJobSumMachineReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkDepositReport> TblMasterActualJobMCSBulkDepositReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkJammed> TblMasterActualJobMCSBulkJammed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkRetract> TblMasterActualJobMCSBulkRetract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinBulkNoteCollect> TblMasterActualJobMCSCoinBulkNoteCollect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashAdd> TblMasterActualJobMCSCoinCashAdd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashReturn> TblMasterActualJobMCSCoinCashReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinMachineBalance> TblMasterActualJobMCSCoinMachineBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinSuspectFake> TblMasterActualJobMCSCoinSuspectFake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingCashRecycling> TblMasterActualJobMCSRecyclingCashRecycling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingMachineReport> TblMasterActualJobMCSRecyclingMachineReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSBulkSuspectFake> TblMasterActualJobMCSBulkSuspectFake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMobileATMCheckListEE> TblMobileATMCheckListEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCITDelivery> TblMasterActualJobMCSCITDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSRecyclingActualCount> TblMasterActualJobMCSRecyclingActualCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobSumCashAdd> TblMasterActualJobSumCashAdd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTransactionRouteOptimizationHeader_Detail_Item> TblTransactionRouteOptimizationHeader_Detail_Item { get; set; }
        public virtual TblSystemRouteOptimizationStatus TblSystemRouteOptimizationStatus { get; set; }
    }
}
