//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterCommodity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterCommodity()
        {
            this.TblLeedToCashProduct_ProductAttribute_Discrepancy = new HashSet<TblLeedToCashProduct_ProductAttribute_Discrepancy>();
            this.TblLeedToCashProduct_ProductAttribute_Limit_Items = new HashSet<TblLeedToCashProduct_ProductAttribute_Limit_Items>();
            this.TblMasterCommodityCountry = new HashSet<TblMasterCommodityCountry>();
            this.TblVaultBalanceNonbarcode = new HashSet<TblVaultBalanceNonbarcode>();
            this.TblVaultBalance_Discrepancy = new HashSet<TblVaultBalance_Discrepancy>();
        }
    
        public System.Guid Guid { get; set; }
        public string CommodityName { get; set; }
        public Nullable<bool> FlagRequireSeal { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTimeOffset> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagDefaultForMobile { get; set; }
        public bool FlagCommodityGlobal { get; set; }
        public Nullable<double> CommodityAmount { get; set; }
        public Nullable<double> CommodityValue { get; set; }
        public string CommodityCode { get; set; }
        public string DenoText { get; set; }
        public string ColumnInReport { get; set; }
        public Nullable<System.Guid> SystemGlobalUnit_Guid { get; set; }
        public Nullable<System.Guid> MasterCommodityGroup_Guid { get; set; }
        public bool FlagNonBarcodeSeal { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct_ProductAttribute_Discrepancy> TblLeedToCashProduct_ProductAttribute_Discrepancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct_ProductAttribute_Limit_Items> TblLeedToCashProduct_ProductAttribute_Limit_Items { get; set; }
        public virtual TblMasterCommodityGroup TblMasterCommodityGroup { get; set; }
        public virtual TblSystemGlobalUnit TblSystemGlobalUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCommodityCountry> TblMasterCommodityCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalanceNonbarcode> TblVaultBalanceNonbarcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy { get; set; }
    }
}
