//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterNemoDetailRouteOptimization
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterNemoQueueRouteOptimization_Guid { get; set; }
        public string NodesPlanned { get; set; }
        public string BranchCodeReference { get; set; }
        public string Arrivals { get; set; }
        public string Departures { get; set; }
        public Nullable<int> NumberNodes { get; set; }
        public Nullable<decimal> DistanceOptimized { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public Nullable<int> DurationTime { get; set; }
        public Nullable<System.DateTime> Travel { get; set; }
        public Nullable<int> TravelTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string Unserved { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public Nullable<int> StopOrder { get; set; }
    
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblMasterNemoQueueRouteOptimization TblMasterNemoQueueRouteOptimization { get; set; }
    }
}
