//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRouteJobHeader
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterRoute_Guid { get; set; }
        public Nullable<System.Guid> SystemStopType_Guid { get; set; }
        public Nullable<System.Guid> SystemLineOfBusiness_Guid { get; set; }
        public Nullable<System.Guid> SystemServiceJobType_Guid { get; set; }
        public Nullable<int> DayInVault { get; set; }
        public Nullable<System.Guid> MasterCustomerContract_Guid { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<int> OnwardDestinationType { get; set; }
        public Nullable<System.Guid> OnwardDestination_Guid { get; set; }
        public Nullable<System.Guid> SystemTripIndicator_Guid { get; set; }
        public Nullable<System.Guid> MasterSubServiceType_Guid { get; set; }
        public bool FlagJobInterBranch { get; set; }
        public bool FlagJobMultiBranch { get; set; }
        public Nullable<System.Guid> MasterSitePathHeader_Guid { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<System.Guid> SystemMasterRouteJobNotAllowGenerateReason_Guid { get; set; }
    
        public virtual TblMasterSitePathHeader TblMasterSitePathHeader { get; set; }
    }
}
