//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRunResource_Maintenance_Detail
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterRunResource_Maintenance_Guid { get; set; }
        public Nullable<System.Guid> MasterMaintenanceCategory_Items_Guid { get; set; }
        public Nullable<int> Part_Qty_Estimate { get; set; }
        public Nullable<decimal> Unite_Price_Estimate { get; set; }
        public Nullable<int> Discount_Type_Estimate { get; set; }
        public Nullable<double> Discount_Estimate { get; set; }
        public Nullable<int> Part_Qty_Actual { get; set; }
        public Nullable<decimal> Unite_Price_Actual { get; set; }
        public Nullable<int> Discount_Type_Acutal { get; set; }
        public Nullable<double> Discount_Actual { get; set; }
        public Nullable<System.Guid> MasterMaintenanceCategory_Guid { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Total_Estimate { get; set; }
        public Nullable<decimal> Total_Actual { get; set; }
    }
}
