//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterUser()
        {
            this.TblLeedToCashQuotation = new HashSet<TblLeedToCashQuotation>();
            this.TblLeedToCashQuotation1 = new HashSet<TblLeedToCashQuotation>();
            this.TblMasterCustomerContract = new HashSet<TblMasterCustomerContract>();
            this.TblMasterSalesTeamUserMapping = new HashSet<TblMasterSalesTeamUserMapping>();
            this.TblMasterUserLimitedTimeAccess = new HashSet<TblMasterUserLimitedTimeAccess>();
        }
    
        public System.Guid Guid { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string IdentificationNumber { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.Guid> MasterCustomer_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public System.Guid MasterTitleName_Guid { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.Guid MasterSex_Guid { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.Guid> MasterDistrict_Guid { get; set; }
        public string StateName { get; set; }
        public Nullable<System.Guid> MasterCity_Guid { get; set; }
        public Nullable<System.Guid> MasterCountry_Guid { get; set; }
        public bool FlagCustomer { get; set; }
        public Nullable<System.Guid> SystemDomain_Guid { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> LastDateTimeLogin { get; set; }
        public Nullable<bool> FlagChangePWDNextLogIn { get; set; }
        public Nullable<bool> FlagLock { get; set; }
        public Nullable<int> CountInvalidLogOn { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string PersonImage { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> SystemLanguage_Guid { get; set; }
        public Nullable<System.Guid> SystemFormat_Date_Guid { get; set; }
        public Nullable<System.Guid> SystemFormat_NumberCurrency_Guid { get; set; }
        public Nullable<System.Guid> SystemUserRole_Guid { get; set; }
        public Nullable<System.Guid> MasterCurrency_Default_Guid { get; set; }
        public bool FlagApprove { get; set; }
        public bool FlagDisable { get; set; }
        public Nullable<bool> FlagCanApprove { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<bool> FlagSupervisorVerification { get; set; }
        public Nullable<System.Guid> SaltKey { get; set; }
        public Nullable<System.Guid> MasterCountry_State_Guid { get; set; }
        public string CitryName { get; set; }
        public string OktaUid { get; set; }
        public Nullable<System.Guid> MasterPrevault_Guid { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<bool> FlagLimitedTimeAccess { get; set; }
        public string CurrentSession { get; set; }
        public Nullable<System.Guid> MasterSalesLevel_Guid { get; set; }
        public bool FlagSalePerson { get; set; }
        public bool FlagAllUpdateHistoricJob { get; set; }
        public Nullable<System.Guid> SystemDomainAlies_Guid { get; set; }
        public Nullable<System.Guid> MasterMenuDetail_Guid { get; set; }
        public bool FlagSkipSSO { get; set; }
        public bool FlagCentralOverride { get; set; }
        public bool FlagRouteMonitoring { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation> TblLeedToCashQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation> TblLeedToCashQuotation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerContract> TblMasterCustomerContract { get; set; }
        public virtual TblMasterSalesLevel TblMasterSalesLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSalesTeamUserMapping> TblMasterSalesTeamUserMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterUserLimitedTimeAccess> TblMasterUserLimitedTimeAccess { get; set; }
    }
}
