//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobItemsCommodity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterActualJobItemsCommodity()
        {
            this.TblVaultBalance_Discrepancy = new HashSet<TblVaultBalance_Discrepancy>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobHeader_Guid { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> QuantityActual { get; set; }
        public Nullable<int> QuantityExpected { get; set; }
        public Nullable<bool> FlagCommodityDiscrepancies { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartment_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartmentArea_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartmentSubArea_Guid { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string Master_ID { get; set; }
        public Nullable<System.Guid> MasterActualJobItemsLiability_Guid { get; set; }
        public Nullable<bool> FlagPartial { get; set; }
        public Nullable<System.Guid> MasterReasonUnableToServiceGuid { get; set; }
        public string Comment { get; set; }
        public string MasterID_Route { get; set; }
        public Nullable<bool> FlagConsolidate { get; set; }
        public string MasterID_DP { get; set; }
        public string MasterID_Route_DP { get; set; }
        public bool FlagRouteBalance { get; set; }
        public Nullable<int> QtyRouteBalance { get; set; }
        public string ConsolidateLocationMode { get; set; }
        public Nullable<System.Guid> MasterConAndDeconsolidateHeaderMasterIDRoute_Guid { get; set; }
        public Nullable<System.Guid> MasterConAndDeconsolidateHeaderMasterID_Guid { get; set; }
        public string OldMasterId { get; set; }
        public string OldMasterIdRoute { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalance_Discrepancy> TblVaultBalance_Discrepancy { get; set; }
    }
}
