//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterSiteNetworkMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMasterSiteNetworkMember()
        {
            this.TblMasterSiteNetworkUsergroup = new HashSet<TblMasterSiteNetworkUsergroup>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterSiteNetwork_Guid { get; set; }
        public System.Guid MasterSite_Guid { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
    
        public virtual TblMasterSiteNetwork TblMasterSiteNetwork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSiteNetworkUsergroup> TblMasterSiteNetworkUsergroup { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
    }
}
