//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterRoute_OptimizationStatus
    {
        public System.Guid Guid { get; set; }
        public System.Guid MasterRoute_Guid { get; set; }
        public System.Guid MasterRouteGroupDetail_Guid { get; set; }
        public System.Guid SystemRouteOptimizationStatus_Guid { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
    
        public virtual TblMasterRoute TblMasterRoute { get; set; }
        public virtual TblMasterRouteGroup_Detail TblMasterRouteGroup_Detail { get; set; }
        public virtual TblSystemRouteOptimizationStatus TblSystemRouteOptimizationStatus { get; set; }
    }
}
