//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMasterActualJobItemUnknow
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterRunResourceDaily_Guid { get; set; }
        public string SealNo { get; set; }
        public Nullable<System.Guid> MasterCommodity_Guid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> FlagMatchDone { get; set; }
        public string ClientHostNameScan { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string UsernameSupervisorVerify { get; set; }
        public Nullable<System.DateTime> DatetimeSupervisorVerify { get; set; }
        public Nullable<System.Guid> MasterReasonType_Guid { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartment_Guid { get; set; }
    }
}
