//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPricingRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPricingRule()
        {
            this.TblChargeCategory = new HashSet<TblChargeCategory>();
            this.TblLeedToCashContract_PricingRules = new HashSet<TblLeedToCashContract_PricingRules>();
            this.TblLeedToCashContract_PricingRules1 = new HashSet<TblLeedToCashContract_PricingRules>();
            this.TblLeedToCashQuotation_Customer_Mapping = new HashSet<TblLeedToCashQuotation_Customer_Mapping>();
            this.TblLeedToCashQuotation_Location_Mapping = new HashSet<TblLeedToCashQuotation_Location_Mapping>();
            this.TblLeedToCashQuotation_PricingRule_Mapping = new HashSet<TblLeedToCashQuotation_PricingRule_Mapping>();
            this.TblLeedToCashQuotation_PricingRule_Mapping1 = new HashSet<TblLeedToCashQuotation_PricingRule_Mapping>();
            this.TblMasterCustomerContract_ServiceLocation = new HashSet<TblMasterCustomerContract_ServiceLocation>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid Product_Guid { get; set; }
        public string Name { get; set; }
        public System.Guid MasterCurrency_Guid { get; set; }
        public string WordShownInTariff { get; set; }
        public int SeqNo { get; set; }
        public string UserCreated { get; set; }
        public System.DateTimeOffset DatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public System.DateTimeOffset DatetimeModified { get; set; }
        public Nullable<System.Guid> MasterPricingRule_Guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChargeCategory> TblChargeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashContract_PricingRules> TblLeedToCashContract_PricingRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashContract_PricingRules> TblLeedToCashContract_PricingRules1 { get; set; }
        public virtual TblLeedToCashProduct TblLeedToCashProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation_Customer_Mapping> TblLeedToCashQuotation_Customer_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation_Location_Mapping> TblLeedToCashQuotation_Location_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation_PricingRule_Mapping> TblLeedToCashQuotation_PricingRule_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashQuotation_PricingRule_Mapping> TblLeedToCashQuotation_PricingRule_Mapping1 { get; set; }
        public virtual TblMasterCurrency TblMasterCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerContract_ServiceLocation> TblMasterCustomerContract_ServiceLocation { get; set; }
    }
}
