//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemEnvironmentMasterSiteValue
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> SystemEnvironmentMasterCountry_Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public string AppValue1 { get; set; }
        public string AppValue2 { get; set; }
        public string AppValue3 { get; set; }
        public string AppValue4 { get; set; }
        public string AppValue5 { get; set; }
        public string AppValue6 { get; set; }
        public string AppValue7 { get; set; }
        public string AppValue8 { get; set; }
        public string AppValue9 { get; set; }
    }
}
