//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemJobHideScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSystemJobHideScreen()
        {
            this.TblMasterActualJobHideScreenMapping = new HashSet<TblMasterActualJobHideScreenMapping>();
            this.TblMasterCustomer_JobHideScreen = new HashSet<TblMasterCustomer_JobHideScreen>();
            this.TblSystemJobHideField = new HashSet<TblSystemJobHideField>();
        }
    
        public System.Guid Guid { get; set; }
        public string ScreenName { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DatetimeModify { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModify { get; set; }
        public bool FlagDisable { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobHideScreenMapping> TblMasterActualJobHideScreenMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomer_JobHideScreen> TblMasterCustomer_JobHideScreen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSystemJobHideField> TblSystemJobHideField { get; set; }
    }
}
