//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemNotificationConfigPeriods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSystemNotificationConfigPeriods()
        {
            this.TblSystemNotificationConfigPeriodsUsers = new HashSet<TblSystemNotificationConfigPeriodsUsers>();
        }
    
        public System.Guid Guid { get; set; }
        public System.Guid MasterCountry_Guid { get; set; }
        public string PeriodTitle { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.Guid SystemEnvironmentMasterCountry_Guid { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public bool FlagDisable { get; set; }
    
        public virtual TblMasterCountry TblMasterCountry { get; set; }
        public virtual TblSystemEnvironmentMasterCountry TblSystemEnvironmentMasterCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSystemNotificationConfigPeriodsUsers> TblSystemNotificationConfigPeriodsUsers { get; set; }
    }
}
