//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemEmailAction
    {
        public System.Guid Guid { get; set; }
        public string ActionName { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public System.DateTimeOffset UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DateTimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public Nullable<int> ActionID { get; set; }
    }
}
