//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemNotificationConfigPeriodsUsers
    {
        public System.Guid Guid { get; set; }
        public System.Guid SystemNotificationConfigPeriods_Guid { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> ExternalUser { get; set; }
        public string EscalationEmail { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public bool FlagDisable { get; set; }
    
        public virtual TblSystemNotificationConfigPeriods TblSystemNotificationConfigPeriods { get; set; }
    }
}
