//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemRunningValue_Custom
    {
        public System.Guid Guid { get; set; }
        public string RunningKey { get; set; }
        public int RunningValue1 { get; set; }
        public int RunningValue2 { get; set; }
        public int RunningValue3 { get; set; }
        public int RunningValue4 { get; set; }
        public int RunningValue5 { get; set; }
        public string ReferenceValue1 { get; set; }
        public string ReferenceValue2 { get; set; }
        public string ReferenceValue3 { get; set; }
        public string ReferenceValue4 { get; set; }
        public string ReferenceValue5 { get; set; }
    }
}
