//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemLeedToCashStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSystemLeedToCashStatus()
        {
            this.TblLeedToCashMasterClause = new HashSet<TblLeedToCashMasterClause>();
            this.TblLeedToCashProduct = new HashSet<TblLeedToCashProduct>();
            this.TblLeedToCashProduct_ProductAttribute = new HashSet<TblLeedToCashProduct_ProductAttribute>();
        }
    
        public System.Guid Guid { get; set; }
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public bool FlagDisable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashMasterClause> TblLeedToCashMasterClause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct> TblLeedToCashProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLeedToCashProduct_ProductAttribute> TblLeedToCashProduct_ProductAttribute { get; set; }
    }
}
