//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemLog_Activity
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> SystemActivity_ID { get; set; }
        public string Activity { get; set; }
        public string UseID { get; set; }
        public string ClientIP { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.Guid> SystemApplication_Guid { get; set; }
    
        public virtual TblSystemApplication TblSystemApplication { get; set; }
    }
}
