//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemEnvironmentMasterCountryTreeView
    {
        public System.Guid Guid { get; set; }
        public int NodeParentId { get; set; }
        public int NodeIndexId { get; set; }
        public int NodeOrderingNo { get; set; }
        public string NodeName { get; set; }
        public bool FlagDisable { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public System.Guid SystemEnvironmentMasterCountry_Guid { get; set; }
    
        public virtual TblSystemEnvironmentMasterCountry TblSystemEnvironmentMasterCountry { get; set; }
    }
}
