//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemDisplayTextControlsLanguage
    {
        public System.Guid Guid { get; set; }
        public System.Guid SystemLanguageGuid { get; set; }
        public string DisplayText { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public string ReferenceId { get; set; }
    }
}
