//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemServiceJobTypeLOB
    {
        public System.Guid Guid { get; set; }
        public System.Guid SystemLineOfBusinessGuid { get; set; }
        public System.Guid SystemServiceJobTypeGuid { get; set; }
    
        public virtual TblSystemLineOfBusiness TblSystemLineOfBusiness { get; set; }
        public virtual TblSystemServiceJobType TblSystemServiceJobType { get; set; }
    }
}
