//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemJobStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSystemJobStatus()
        {
            this.SFOTblSystemAllowServiceRequestStatusDuplicate = new HashSet<SFOTblSystemAllowServiceRequestStatusDuplicate>();
            this.SFOTblSystemEscalationRuleHeader = new HashSet<SFOTblSystemEscalationRuleHeader>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<int> StatusJobID { get; set; }
        public string StatusJobName { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControlsLanguage_Guid { get; set; }
        public Nullable<bool> FlagScanByPreVault { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string PathIcon { get; set; }
        public Nullable<bool> FlagCloseRun { get; set; }
        public Nullable<bool> FlagUpdateJobClose { get; set; }
        public string ImagePathMVC { get; set; }
        public Nullable<bool> FlagIncidentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemAllowServiceRequestStatusDuplicate> SFOTblSystemAllowServiceRequestStatusDuplicate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblSystemEscalationRuleHeader> SFOTblSystemEscalationRuleHeader { get; set; }
    }
}
