//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemRouteOptimizationRouteType_RequestType
    {
        public System.Guid Guid { get; set; }
        public System.Guid SystemRouteOptimizationRouteType_Guid { get; set; }
        public System.Guid SystemRouteOptimizationRequestType_Guid { get; set; }
    
        public virtual TblSystemRouteOptimizationRouteType TblSystemRouteOptimizationRouteType { get; set; }
        public virtual TblSystemRouteOptimizationRequestType TblSystemRouteOptimizationRequestType { get; set; }
    }
}
