//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemCassetteType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSystemCassetteType()
        {
            this.TblMasterActualJobMCSCoinCashAddEntry = new HashSet<TblMasterActualJobMCSCoinCashAddEntry>();
            this.TblMasterActualJobMCSCoinCashReturnEntry = new HashSet<TblMasterActualJobMCSCoinCashReturnEntry>();
            this.TblMasterActualJobMCSCoinMachineBalanceEntry = new HashSet<TblMasterActualJobMCSCoinMachineBalanceEntry>();
            this.SFOTblMasterCassette = new HashSet<SFOTblMasterCassette>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<int> InternalID { get; set; }
        public string CTName { get; set; }
        public string CTAbbreviationName { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> SystemDisplayTextControls_Guid { get; set; }
        public string ReferenceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashAddEntry> TblMasterActualJobMCSCoinCashAddEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinCashReturnEntry> TblMasterActualJobMCSCoinCashReturnEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterActualJobMCSCoinMachineBalanceEntry> TblMasterActualJobMCSCoinMachineBalanceEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFOTblMasterCassette> SFOTblMasterCassette { get; set; }
    }
}
