//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSystemLineOfBusiness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSystemLineOfBusiness()
        {
            this.TblMasterCustomerLocation_ServiceHour = new HashSet<TblMasterCustomerLocation_ServiceHour>();
            this.TblMasterSubLob = new HashSet<TblMasterSubLob>();
            this.TblMasterSubServiceType = new HashSet<TblMasterSubServiceType>();
            this.TblSystemServiceJobTypeLOB = new HashSet<TblSystemServiceJobTypeLOB>();
            this.TblMasterCustomer_JobHideScreen = new HashSet<TblMasterCustomer_JobHideScreen>();
        }
    
        public System.Guid Guid { get; set; }
        public string ExternalID { get; set; }
        public Nullable<int> InternalID { get; set; }
        public string LOBFullName { get; set; }
        public string LOBSystemName { get; set; }
        public string LOBAbbrevaitionName { get; set; }
        public string LOBReportName { get; set; }
        public Nullable<int> Premise_Time { get; set; }
        public Nullable<bool> FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModifed { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public string ReferenceId { get; set; }
        public string AvailableOnVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomerLocation_ServiceHour> TblMasterCustomerLocation_ServiceHour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSubLob> TblMasterSubLob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterSubServiceType> TblMasterSubServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSystemServiceJobTypeLOB> TblSystemServiceJobTypeLOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMasterCustomer_JobHideScreen> TblMasterCustomer_JobHideScreen { get; set; }
    }
}
