//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTempMainPrevaultReport
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> DailyRunResource_Guid { get; set; }
        public Nullable<System.Guid> RouteGroupDetail_Guid { get; set; }
        public string RunResourceNo { get; set; }
        public string ShipperName { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<int> ExpectedQty { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public Nullable<System.DateTime> DateTimeScan { get; set; }
        public Nullable<System.Guid> MasterSiteFrom_Guid { get; set; }
        public Nullable<System.Guid> MasterSiteTo_Guid { get; set; }
        public Nullable<System.Guid> Prevault_Guid { get; set; }
        public string PrevaultName { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string RptAction { get; set; }
        public int ScanSeq { get; set; }
        public Nullable<System.Guid> InternalDepartment_Guid { get; set; }
        public string RouteNo { get; set; }
    }
}
