//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTempPrevaultSealReport
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> TempMainPrevaultReport_Guid { get; set; }
        public Nullable<System.Guid> SystemReportStyle_Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobHeader_Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobItemsSeal_Guid { get; set; }
        public string LocationName { get; set; }
        public string ConsolidateRouteID { get; set; }
        public string ConsolidateLocationID { get; set; }
        public string SealNo { get; set; }
        public Nullable<int> ExpectedQty { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public Nullable<int> ShortageQty { get; set; }
        public Nullable<int> OverageQty { get; set; }
        public Nullable<double> LiabilityValue { get; set; }
        public bool FlagPartial { get; set; }
        public string TitleNameReport { get; set; }
        public bool FlagRptNonDelivery { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public Nullable<System.Guid> LiabilityGuid { get; set; }
        public Nullable<System.Guid> CurrencyGuid { get; set; }
        public string SealNoReplace { get; set; }
        public string OldMasterId { get; set; }
        public string OldMasterIdRoute { get; set; }
    }
}
