//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransactionRouteOptimizationHeader_Detail_Item
    {
        public System.Guid Guid { get; set; }
        public System.Guid TransactionRouteOptimizationHeader_Detail_Guid { get; set; }
        public string RequestItemID { get; set; }
        public Nullable<System.Guid> MasterRouteJobServiceStopLegs_Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobServiceStopLegs_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_Guid { get; set; }
        public Nullable<int> SequenceBefore { get; set; }
        public Nullable<int> SequenceAfter { get; set; }
        public bool FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeModified { get; set; }
        public Nullable<System.Guid> SystemServiceJobType_Guid { get; set; }
    
        public virtual TblMasterActualJobServiceStopLegs TblMasterActualJobServiceStopLegs { get; set; }
        public virtual TblMasterCustomerLocation TblMasterCustomerLocation { get; set; }
        public virtual TblMasterRouteJobServiceStopLegs TblMasterRouteJobServiceStopLegs { get; set; }
        public virtual TblTransactionRouteOptimizationHeader_Detail TblTransactionRouteOptimizationHeader_Detail { get; set; }
        public virtual TblSystemServiceJobType TblSystemServiceJobType { get; set; }
    }
}
