//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVaultBalanceSealAndMaster
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> VaultBalanceHeader_Guid { get; set; }
        public Nullable<System.Guid> MasterActualJobItemsSeal_Guid { get; set; }
        public Nullable<System.Guid> MasterConAndDeconsolidate_Header_Guid { get; set; }
        public string SealNo { get; set; }
        public Nullable<System.Guid> MasterActualJobHeader_Guid { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.Guid> MasterActualJobItemsLiability_Guid { get; set; }
        public double STC { get; set; }
        public string CommodityName { get; set; }
        public string Currency { get; set; }
        public string MasterCustomer_Location_Pickup { get; set; }
        public string MasterCustomer_Location_Delivery { get; set; }
        public string SystemServiceJobTypeName { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public Nullable<System.DateTimeOffset> UniversalDatetimeCreated { get; set; }
    
        public virtual TblMasterActualJobHeader TblMasterActualJobHeader { get; set; }
        public virtual TblMasterActualJobItemsLiability TblMasterActualJobItemsLiability { get; set; }
        public virtual TblMasterActualJobItemsSeal TblMasterActualJobItemsSeal { get; set; }
        public virtual TblMasterConAndDeconsolidate_Header TblMasterConAndDeconsolidate_Header { get; set; }
        public virtual TblVaultBalanceHeader TblVaultBalanceHeader { get; set; }
    }
}
