//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVaultBalanceNonbarcode
    {
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> VaultBalanceHeader_Guid { get; set; }
        public Nullable<System.Guid> Commodity_Guid { get; set; }
        public int PreAdviceQty { get; set; }
        public int ActualQty { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
    
        public virtual TblMasterCommodity TblMasterCommodity { get; set; }
        public virtual TblVaultBalanceHeader TblVaultBalanceHeader { get; set; }
    }
}
