//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVaultBalanceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblVaultBalanceHeader()
        {
            this.TblVaultBalanceDetail = new HashSet<TblVaultBalanceDetail>();
            this.TblVaultBalanceNonbarcode = new HashSet<TblVaultBalanceNonbarcode>();
            this.TblVaultBalanceSealAndMaster = new HashSet<TblVaultBalanceSealAndMaster>();
        }
    
        public System.Guid Guid { get; set; }
        public Nullable<System.Guid> MasterSite_Guid { get; set; }
        public Nullable<System.Guid> MasterCustomerLocation_InternalDepartment_Guid { get; set; }
        public Nullable<int> StateID { get; set; }
        public string UsernameSupervisorVerify { get; set; }
        public Nullable<System.DateTime> DatetimeSupervisorVerify { get; set; }
        public int Seal_PreAdviceQty { get; set; }
        public int Seal_ActualQty { get; set; }
        public int Seal_ShortageQty { get; set; }
        public string Seal_ShortageList { get; set; }
        public int Seal_OverageQty { get; set; }
        public string Seal_OverageList { get; set; }
        public int LocationMasterSeal_PreAdviceQty { get; set; }
        public int LocationMasterSeal_ActualQty { get; set; }
        public int RouteMasterSeal_PreAdviceQty { get; set; }
        public int RouteMasterSeal_ActualQty { get; set; }
        public int PreviousStateID { get; set; }
        public bool FlagModeBlind { get; set; }
    
        public virtual TblMasterCustomerLocation_InternalDepartment TblMasterCustomerLocation_InternalDepartment { get; set; }
        public virtual TblMasterSite TblMasterSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalanceDetail> TblVaultBalanceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalanceNonbarcode> TblVaultBalanceNonbarcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVaultBalanceSealAndMaster> TblVaultBalanceSealAndMaster { get; set; }
    }
}
