//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bgt.Ocean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWebAPIUserApplication
    {
        public System.Guid Guid { get; set; }
        public System.Guid WebAPIUser_Guid { get; set; }
        public System.Guid SystemApplication_Guid { get; set; }
    
        public virtual TblSystemApplication TblSystemApplication { get; set; }
        public virtual TblWebAPIUser TblWebAPIUser { get; set; }
    }
}
