using System;

namespace Bgt.Ocean.Service.ModelViews.ServiceRequest
{
    public class CreateServiceRequestView
    {
        public Guid? Guid { get; set; }
        public int DateStatus { get; set; }
        public Guid? MasterSite_Guid { get; set; }
        public Guid? MasterActualJobHeader_Guid { get; set; }
        public Guid? MasterCustomerLocation_Guid { get; set; }
        public Guid? SFOMasterCategory_Guid { get; set; }
        public Guid? SFOMasterServiceRequestType_Guid { get; set; }
        public Guid? SFOMasterPriority_Guid { get; set; }
        public Guid? SFOMasterSource_OpenSource_Guid { get; set; }
        public Guid? SFOMasterSource_CloseSource_Guid { get; set; }
        public Guid? SFOMasterReason_Guid { get; set; }
        public string TicketNumber { get; set; }
        public Guid? TicketStatus_Guid { get; set; }
        public DateTime? RequestedServiceDate { get; set; }
        public DateTime? DateTimeOpened { get; set; }
        public DateTime? DateTimeClosed { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string CustomerReferenceNumber { get; set; }
        public string ResponderReferenceNumber { get; set; }
        public string EscalationType { get; set; }
        public int? EscalationLevel { get; set; }
        public DateTime? EscalationTime { get; set; }
        public DateTime? DateTimeNotified { get; set; }
        public string ReportedServiceRequestDescription { get; set; }
        public string ECashDenomination { get; set; }
        public int? ECashAmount { get; set; }
        public string ECashCurrency { get; set; }
        public string TechMeetName { get; set; }
        public string TechMeetPhone { get; set; }
        public string TechMeetCompanyName { get; set; }
        public string TechMeetReasonID { get; set; }
        public string TechMeetSecurityRequired { get; set; }
        public string CreatedBy { get; set; }
        public bool? FlagRescheduleRequest { get; set; }
        public Guid? Reason_Guid { get; set; }
        public string ResolvedBy { get; set; }
        public string VendorSolutionID { get; set; }
        public bool? FlagBillableIndicator { get; set; }
        public DateTime? CalculatedDueDateTime { get; set; }
        public bool? FlagNotifyNow { get; set; }
        public string Technician { get; set; }
        public DateTime? DateTimeAcknowledged { get; set; }
        public DateTime? DateTimeETA { get; set; }
        public DateTime? DateTimeDepartureToOnsite { get; set; }
        public DateTime? DateTimeReportedOnsite { get; set; }
        public DateTime? DateTimeReportedResolved { get; set; }
        public DateTime? DateTimeReportedDeparted { get; set; }
        public DateTime? DateTimeReportedReturned { get; set; }
        public DateTime? DateTimeDateTimeDown { get; set; }
        public DateTime? DateTimeDispatched { get; set; }
        public DateTime? DateTimeCustomerStart { get; set; }
        public DateTime? DateTimeCustomerDispatched { get; set; }
        public int? TotalPremiseTime { get; set; }
        public Guid? MassServiceRequest_Guid { get; set; }
        public string PACNCode { get; set; }
        public DateTime? DateTimeRequestedNotification { get; set; }
        public string CancellationReason { get; set; }
        public string CustomerCommentIn { get; set; }
        public string CustomerCommentOut { get; set; }
        public string CustomerNetworkID { get; set; }
        public string VendorNetworkID { get; set; }
        public string FileReference { get; set; }
        public string VendorCommentIn { get; set; }
        public string VendorCommentOut { get; set; }
        public string Owner { get; set; }
        public Guid? OwnerSource_Guid { get; set; }
        public bool? FlagClosedOnFirstContact { get; set; }
        public string BrinksLogNumber { get; set; }
        public bool? FlagNonbillableToBranch { get; set; }
        public bool? FlagNonbillableToCustomer { get; set; }
        public bool? FlagSpecialCharges { get; set; }
        public decimal? ChargeAmount { get; set; }
        public bool? FlagRescheduleApproved { get; set; }
        public bool? FlagDisable { get; set; }
        public string UserCreated { get; set; }
        public DateTimeOffset? DatetimeCreated { get; set; }
        public DateTimeOffset? UniversalDatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public DateTimeOffset? DatetimeModified { get; set; }
        public DateTimeOffset? universalDatetimeModified { get; set; }
        public Guid? TimeZoneLocal_Guid { get; set; }
        public Guid? TimeZoneMachine_Guid { get; set; }
        public string BrinksNote { get; set; }
        public string ReasonName { get; set; }
        public DateTime? DateTimeDueDate { get; set; }
        public DateTime? DateTimeServiceDate { get; set; }
        public bool? FlagStampDispatch { get; set; }
        public bool? FlagStampAccept { get; set; }
        public bool? FlagStampETA { get; set; }
        public bool? FlagStampArrive { get; set; }
        public bool? FlagStampReportedOnsite { get; set; }
        public bool? FlagStampRestore { get; set; }
        public bool? FlagStampDepart { get; set; }
        public bool? FlagStampReturn { get; set; }
        public string CancelReason { get; set; }
        public string ResponderName { get; set; }
        public Guid? PreviousTicketStatusGuid { get; set; }
        public bool? flagTechMeetSecurityRequired { get; set; }
        public string ReportedDescription { get; set; }
        public Guid? ParentTicketGuid { get; set; }
        public Guid? MasterDailyRunResource_Guid { get; set; }
        public string ResponderStatus { get; set; }
        public string RescheduleReason { get; set; }
        public bool? FlagCloseOTC { get; set; }
        public string ResponderEmail { get; set; }
        public string ResponderShift { get; set; }
        public bool FlagATM { get; set; }
        public bool FlagFLM { get; set; }
        public bool FlagCompuSafe { get; set; }
        public string MassRequestID { get; set; }
        public bool FlagEcash { get; set; }
        public Guid? PreviousServiceRequestState_Guid { get; set; }
        public int EnvBranchTypeId { get; set; }
        public bool FlagBranchVendor { get; set; }
        public Guid? SFOMasterMachineServiceType_Guid { get; set; }
        public bool FlagOnHold { get; set; }
    }
}
